### ISSUE TITLE
jetty-web.xml doesn't work with the HttpServiceContext as it does with the WebContext [PAXWEB-734]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1027]
**[Achim Nierbeck](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:fe7441d2-0e52-4f37-8e07-214aa8051d84)** created **[PAXWEB-734](https://ops4j1.jira.com/browse/PAXWEB-734)** 

Either the HttpServiceContext must inherit from WebContext or all of the WebContext methods must be available for HttpServiceContext too

---

**Fixed in:** (non fixable)
Votes: 1, Watches: 3

**Comment by alienintheheights** [comment]
One of the missing WebAppContext methods in the pax.web HttpServiceContext is [overrideDescriptor](https://docs.huihoo.com/jetty/the-definitive-reference/override-web-xml.html) which we'd like to set in our jetty-web.xml. Is there a workaround?

**Comment by grgrzybek** [comment]
The hierarchy of contexts in Jetty is:
```
org.eclipse.jetty.server.handler.AbstractHandler
+-- org.eclipse.jetty.server.handler.AbstractHandlerContainer
    +-- org.eclipse.jetty.server.handler.HandlerWrapper
        +-- org.eclipse.jetty.server.handler.ScopedHandler
            +-- org.eclipse.jetty.server.handler.ContextHandler
                +-- org.eclipse.jetty.servlet.ServletContextHandler
                    +-- org.eclipse.jetty.webapp.WebAppContext
                    +-- org.ops4j.pax.web.service.jetty.internal.HttpServiceContext
```
Pax Web's `HttpServiceContext` extends `ServletContextHandler`, not `WebAppContext` and this can't be changed.

Unfortunately I see no chance to rewrite this... I'm quite actively working on Pax Web 8 (see [main branch](https://github.com/ops4j/org.ops4j.pax.web/commits/main)) and I'm aware of the scenario where you want to override some defaults.
Pax Web 8 already has support to fully parse all `web.xml` and `web-fragment.xml` descriptors in embedded jars, embedded dirs, attached fragments and wired bundles. But Pax Web 8 is still far from GA...

For now I don't have good solution for you about this issue ;(
