### ISSUE TITLE
Make it easier to control the HttpContext of servlets registered on the whiteboard [PAXWEB-819]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1107]
**[Jostein Gogstad](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:0cb692ac-e843-4c58-8e9e-8ed239aeaad7)** created **[PAXWEB-819](https://ops4j1.jira.com/browse/PAXWEB-819)** 

When registering servlets on the whiteboard, pax-web-whiteboard-extender will pick it up and make it available on Jetty. This is described in [http://ops4j.github.io/pax/web/SNAPSHOT/#_servlets](http://ops4j.github.io/pax/web/SNAPSHOT/#_servlets). I believe the way-of-least-surprise would be this

1. If the bundle registering the servlet is a WAB (i.e. it exposes a service of type `org.ops4j.pax.web.service.WebAppDependencyHolder`), then associate the servlet with the HttpContext that already exists for the bundle
1. If the bundle is not a WAB, create a new HttpContext and associate the servlet with this context (unless `ExtenderConstants.PROPERTY_HTTP_CONTEXT_ID` is defined of course).

Point 2. is the implementation for all servlets today. This has several drawbacks

* Any security constraints or other configuration in `web.xml` for the WAB will not be applied to the servlet
* Any configuration in `jetty-web.xml` for the WAB will not be applied to the servlet

Todays impementation assumes use of `ExtenderConstants.PROPERTY_HTTP_CONTEXT_ID` in order to associate a servlet with a HttpContext. This is fine and well, but the HttpContext registered by pax-web for the WAB doesn't have a context id, thus making it impossible to associate a servlet with it.

Proposed changes

1. Make it possible to associate servlets with the HttpContext already created for a WAB through the context id. Maybe by registering the context as a service with that property on the bundle?
1. Introduce the default behaviour described above where servlets are default associated with existing HttpContexts for WABs

---

**Affects:** 3.0.7, 4.1.1
**Fixed in:** future
Votes: 1, Watches: 4

**Comment by grgrzybek** [comment]
Replying in the context of Pax Web 8.

`HttpService` registration scenario (registering a servlet using dedicated method) _associates_ the servlet with default (or custom) context. By _default_ we mean a context with **three** properties:
* it has a context path `/`
* it has a `default` name
* it is scoped to the bundle for which an instance of `HttpService` was obtained.

On the other hand, the context for a WAB:
* has context path from `Web-ContextPath` manifest header (see chapter 128.3.1 WAB Definition of OSGi CMPN)
* doesn't have any special name
* it is still scoped to the WAB bundle

So by default, we **can't** use the same context. Even if `Web-ContextPath` had `/` path.

However there are many improvements and such _reasonable_ behaviors, that I've decided to close this issue as _fixed in Pax Web 8_.
