### ISSUE TITLE
JSF should be able to load resources from other bundles [PAXWEB-895]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1179]
**[Marc Schlegel](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bf96723a-fc46-44ad-a1c6-9916df7773c4)** created **[PAXWEB-895](https://ops4j1.jira.com/browse/PAXWEB-895)** 

In a standard JSF application following Servlet 3.0, JSF is able to load resources (images, templates, pages) from other jar-files.

The mechanism is specified in Servlet 3.0 in the way that resources in a jar must be located under META-INF/resources.<br /> This works fine in global classpath but not in an OSGI-environment because JSF has no API to change the classloader.

The JSF-API defines a so-called ResourceHandler which can be used to load resources from other locations (e.g. a database). The application can configure a custom ResourceHandler-implementation within its faces-config.xml.

This approach can be used for a OSGi-aware ResourceHandler which is able to locate resources in other bundles.<br /> The simplest solution is an extender which checks bundles marked as resource-bundle via a special manifest-header.

---

**Fixed in:** 6.0.0
Votes: 0, Watches: 2

**Comment by grgrzybek** [comment]
With standard WAR/WAB (with `Bundle-ClassPath` including JARs from WAB's `WEB-INF/lib`) resources are loaded fine by Pax Web 8. But I'll keep these bundles in Pax Web 8 as well.
