### ISSUE TITLE
Mark un-needed methods in WebContainer as deprecated [PAXWEB-908]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1190]
**[Achim Nierbeck](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:fe7441d2-0e52-4f37-8e07-214aa8051d84)** created **[PAXWEB-908](https://ops4j1.jira.com/browse/PAXWEB-908)** 

A lot of the methods used in the WebContainer interface can be refactored and therefore declared to be deprecated and be removed later on.

---

**Fixed in:** future
Votes: 0, Watches: 2

**Comment by grgrzybek** [comment]
`WebContainer` interface was changed completely in Pax Web 8.
There's also a new _extension_ method:
```java
default <T extends PaxWebContainerView> T adapt(Class<T> type) {
	return null;
}
```

Which allows to get _under_ the implementation for specific scenario. Both Whiteboard and Web Applications implementations of Pax Web 8 use dedicated WebContainer _views_ in Pax Web 8.
