### ISSUE TITLE
Run tests parallel to reduce execution time [PAXWEB-915]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1196]
**[Achim Nierbeck](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:fe7441d2-0e52-4f37-8e07-214aa8051d84)** created **[PAXWEB-915](https://ops4j1.jira.com/browse/PAXWEB-915)** 

It would be nice if the integration tests could run simultaneous, at least the jetty, tomcat and undertow ones. Karaf ones use to much different ports. <br /> For this it's needed to run Pax-Web with dynamic port and to get the port of the running server.

A first draft can be found in the **tests_with_dynamic_port** branch. <br /> Some tests still fail.<br /> Especially the https ones, but also others where a restart of the container is required.

---

**Fixed in:** future
Votes: 1, Watches: 2

**Comment by grgrzybek** [comment]
Pax Web 8 tests run ~10x faster, so I'm closing this issue.
