### ISSUE TITLE
Creation of Dynamic Connectors doesn't work as expected [PAXWEB-934]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1213]
**[Achim Nierbeck](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:fe7441d2-0e52-4f37-8e07-214aa8051d84)** created **[PAXWEB-934](https://ops4j1.jira.com/browse/PAXWEB-934)** 

---

**Affects:** 4.2.4
**Fixed in:** future
Votes: 1, Watches: 3

**Comment by grgrzybek** [comment]
I've fixed #1666 and for a moment I was thinking that connector tracking was a good idea. But `org.eclipse.jetty.server.ServerConnector` constructor requires a real instance of `org.eclipse.jetty.server.Server`.

Pax Web 8 has much more flexible runtime configuration and also if we want to make it consistent across runtimes, we'd also have to track:
* `org.apache.catalina.connector.Connector` for Tomcat (more flexible than Jetty connector)
* `org.xnio.channels.AcceptingChannel` for Undertow (lot of work with buffers, workers and `org.xnio.OptionMap`s)

I'm closing this issue. If you believe it should be reopened, please specify the reasons.
