### ISSUE TITLE
WebApplication gets removed when mapped servlet is unregistered [PAXWEB-968]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1247]
**[Herr-Herner](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:596a4c24-5039-45a7-8af8-a7181a4f3048)** created **[PAXWEB-968](https://ops4j1.jira.com/browse/PAXWEB-968)** 

I have registered a shared HttpContextMapping with `context.id=test` and now register a servlet with `context.id=test`. The HttpContextMapping specifies to which Jetty connectors the servlet should be bound. Everything works perfectly, the servlet is published and accessible.

Now, the servlet gets unregistered, but the HttpContextMapping keeps registered. The servlet gets unpublished by Pax Web and its WebApplication removed. Now, the servlet gets registered again. It is tracked, but not being published.

The problem is that a new WebApplication is created for this servlet, but its HttpContext is unset. That's the reason why the code in WebApplication.class (line 296) is not being executed:

```java
if (httpService != null && httpContext != null) {
   registerer.register(httpService, httpContext);
}
```

We should find a solution that does not remove the WebApplication instance from the map `webApplications`. This peace of code is the reason why the WebApplication gets removed (AbstractTracker.class, line: 207)

```java
T registered = bundleContext.getService(serviceReference);
if (!remove && Servlet.class.isAssignableFrom(registered.getClass())) {
    //special case where the removed service is a servlet, all other filters etc. should be stopped now too.
    remove = true;
}
bundleContext.ungetService(serviceReference);
```

The webApplication gets removed from the `webApplications` table, but keeps registered in the map `sharedWebApplicationCounter` with a not reduced counter &gt; 0 ( [PAXWEB-967](https://ops4j1.jira.com/browse/PAXWEB-967) ). When the servlet is readded, the associated webApplication cannot be found because the instance is no longer listed. This results in a new object creation.

When the HttpContextMapping itself is removed, we get a `java.lang.NullPointerException` in the `ExtenderContext` (line: 90) caused by a webApplication key that is null. It was looked up in the `AbstractHttpContextTracker` (line: 175) for the HttpContextMapping.

The special case handling in case of a servlet removal should not result in a removal of the webApplication from the table `webApplications`. This behaviour would solve the NullPointerException and would trigger a republication of a servlet that gets associated with an existing HttpContextMapping even when a servlet has been unregistered before.

---

**Affects:** 4.2.5
**Fixed in:** 8.0.0, 6.1.3, 7.0.1, 6.0.13
Votes: 0, Watches: 3

**Comment by grgrzybek** [comment]
Whiteboard tracking has been completely rewritten in Pax Web 8 and each service (servlet, context, filter, error page mapping, listener, ...) is correctly tracked and untracked.
What's more, every _element_ (like servlet) references one ore more _context_ (HttpContext or ServletContextHelper) and Pax Web 8 dynamically re-registers the _element_ when related _contexts_ change.

I'm closing this one as fixed in Pax Web 8.
