### ISSUE TITLE
WebSocket not working with Whiteboard-registration [PAXWEB-1027]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1316]
**[Marc Schlegel](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bf96723a-fc46-44ad-a1c6-9916df7773c4)** created **[PAXWEB-1027](https://ops4j1.jira.com/browse/PAXWEB-1027)** 

Currently registering a WebSocket via Whiteboard fails due to different reasons:

1. The annotation-scan in the tracker fails due to different identities of the class used to check for the annotation.
1. Jetty - If 1. is fixed the HttpServiceStarted times out
1. Undertow - If passed 2. a *javax.websocket.DeploymentException* occurs claiming the class is not annotated correctly (probably same reason as for 1)

**Jetty**

**HttpServerStarted**
```java
javax.websocket.server.ServerContainer serverContainer = (javax.websocket.server.ServerContainer) ctx.getAttribute(javax.websocket.server.ServerContainer.class.getName());
```

this fails because the Jetty adapter never handles the availability of WebSockets. Jetty must be telled to enabled a (Websocket)ServerContainer and provide the attribute in the ServletContext.

**Undertow**<br /> Using Undertow with Whiteboard websockets gets (literally) one step further

**HttpServerStarted**
```java
serverContainer.addEndpoint(webSocket.getClass());
```

this call will end up *ServerWebSocketContainer* (Undertow) which is not able to compare the existing Annotations with each other because they both live in different classloaders (the bundle with the websocket-class and the undertow-lib).

Furthermore *HttpContextStarted* is missing an implementation for unregisterWebsocket.

---

**Affects:** 6.0.0
**Fixed in:** 8.0.0, 6.1.3, 7.0.1, 6.0.13
Votes: 0, Watches: 4

**Comment by grgrzybek** [comment]
@ANierbeck @jbonofre @gnodet @ffang it's finally working! Really!
```java
@Test
public void testWebsocket() throws Exception {
    SimpleWebSocket simpleWebSocket = new SimpleWebSocket();

    Dictionary<String, Object> filter = new Hashtable<>();
    filter.put(PaxWebConstants.SERVICE_PROPERTY_WEBSOCKET, "true");
    context.registerService(Object.class.getName(), simpleWebSocket, filter);

    WebSocketContainer cc = getWebSocketContainer();
    URI uri = new URI("ws://127.0.0.1:8181/simple");
    WebSocketClient client = new WebSocketClient();
    ClassLoader tccl = Thread.currentThread().getContextClassLoader();
    try {
        Bundle tomcatWebSocketClientBundle = bundle(getContainerSpecificWebSocketsBundleSN());
        Thread.currentThread().setContextClassLoader(tomcatWebSocketClientBundle.adapt(BundleWiring.class).getClassLoader());
        Session session = cc.connectToServer(client, uri);

        client.awaitClose(5, TimeUnit.SECONDS);
        session.close();
    } finally {
        Thread.currentThread().setContextClassLoader(tccl);
    }

    String anwer = client.getAnswer();

    assertThat(anwer, equalTo("I got \"Hello\""));
    assertThat(simpleWebSocket.getMessages().size(), equalTo(1));
    assertThat(simpleWebSocket.getMessages().get(0), equalTo("Hello"));
}
```

all SCIs, filters, listeners involved are working - WebSockets are usually implemented by a filter (HTTP → WebSockets upgrade filter) registered dynamically by SCI or a ServletContextListener and I finally managed to handle properly the registration, re-registration, cleanup and restarts of servlet contexts where SCIs/listeners are added dynamically, through Whiteboard and WABs.

**Comment by grgrzybek** [comment]
cc: @lostiniceland
