### ISSUE TITLE
HttpServiceRuntime - calculate InfoDTO from contextroot [PAXWEB-1039]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1329]
**[Marc Schlegel](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bf96723a-fc46-44ad-a1c6-9916df7773c4)** created **[PAXWEB-1039](https://ops4j1.jira.com/browse/PAXWEB-1039)** 

Currently the HttpServiceRuntime.calculateRequestInfoDTO(path) only works if the path matches a dedicated and registered servlet (e.g. /context/my-servlet)

The calculation-method, which is implemented in the runtime-modules WhiteboardDtoService, must be enhanced to match onyl the context-path. The result should inlcude all servlets, filters, and so on which are working within this context.

---

**Affects:** 6.0.0
**Fixed in:** future
Votes: 0, Watches: 1

**Comment by grgrzybek** [comment]
Works fine in Pax Web 8
