### ISSUE TITLE
The documented samples are outdated [PAXWEB-1040]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1330]
**[Achim Nierbeck](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:fe7441d2-0e52-4f37-8e07-214aa8051d84)** created **[PAXWEB-1040](https://ops4j1.jira.com/browse/PAXWEB-1040)** 

---

**Affects:** 6.0.0
**Fixed in:** future
Votes: 0, Watches: 1

**Comment by grgrzybek** [comment]
Follow up: #1476
