### ISSUE TITLE
Enhance ConfigurationImpl to use OSGi encryption service [PAXWEB-1049]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1337]
**[Dariush Amiri](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:b757feae-0957-4bcc-b01b-cfb7b3ab7fe8)** created **[PAXWEB-1049](https://ops4j1.jira.com/browse/PAXWEB-1049)** 

The current Pax Web implementation for encrypting/decrypting configuration properties is problematic because it assumes a specific implementation of a Jasypt property encryptor. Besides the fact that this is an OSGi anti-pattern, it makes it difficult to modify the property encryption and decryption capabilities so they are more secure (e.g. implementing the Jasypt interface so that it offloads encryption and decryption to an HSM).

I would like to propose that rather than simply instantiating a new StandardPBEStringEncryptor, the ConfigurationImpl class should maintain a service tracker for any implementations of org.jasypt.encryption.StringEncryptor registered with the OSGi container. This is the way property encryption/decryption is implemented in Pax JDBC and I feel that it is an overall better approach.

See the following links for reference<br /> [DataSourceConfigManager.java](https://github.com/ops4j/org.ops4j.pax.jdbc/blob/104ae97d991772f0635104f17fbe28501d98575b/pax-jdbc-config/src/main/java/org/ops4j/pax/jdbc/config/impl/DataSourceConfigManager.java)<br /> [Activator.java](https://github.com/ops4j/org.ops4j.pax.jdbc/blob/104ae97d991772f0635104f17fbe28501d98575b/pax-jdbc-config/src/main/java/org/ops4j/pax/jdbc/config/impl/Activator.java)

---

**Fixed in:** 8.0.0, 6.1.3, 7.0.1
Votes: 0, Watches: 2

**Comment by grgrzybek** [comment]
I'll continue the development under #1655
