### ISSUE TITLE
Upgrade to OSGi R7 [PAXWEB-1181]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1354]
**[Jean-Baptiste Onofre](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:ceaddc8e-afbf-4078-a7c0-089234224087)** created **[PAXWEB-1181](https://ops4j1.jira.com/browse/PAXWEB-1181)** 

OSGi R7 provides an updated HTTP service: [https://blog.osgi.org/2018/05/osgi-r7-highlights-http-whiteboard.html](https://blog.osgi.org/2018/05/osgi-r7-highlights-http-whiteboard.html)

Pax Web should support the new annotations and R7 features.

---

**Fixed in:** 8.0.0
Votes: 0, Watches: 2

---
**Referenced issues**

**relates to:**
* #1314 - R7 - Make use of new Capability-Annotations [PAXWEB-1044]

**Comment by grgrzybek** [comment]
Fixed in Pax Web 8.
