### ISSUE TITLE
org.ops4j.pax.web.service.spi.ServerController could use transactional approach to register web elements [PAXWEB-1198]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1361]
**[Grzegorz Grzybek](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:9c7cd322-6f60-46ab-9235-bab9ac2f59f6)** created **[PAXWEB-1198](https://ops4j1.jira.com/browse/PAXWEB-1198)** 

Following [https://groups.google.com/d/msg/ops4j/TF6vqB5PWik/U_X170f_BAAJ](https://groups.google.com/d/msg/ops4j/TF6vqB5PWik/U_X170f_BAAJ) I think it'd be nice to change some pax-web APIs before 8.0.0 release.

---

**Fixed in:** 8.0.0
Votes: 0, Watches: 1

**Comment by grgrzybek** [comment]
Fixed in Pax Web 8. Everything is implemented in terms of "batches of operations" and a _batch_ may be marked as transactional. This is especially important when web elements from WAB (`web.xml` and fragments and annotated elements) are registered for single web application.
