### ISSUE TITLE
jsp-config does not seem to work (ActiveMQ Webconsole) [PAXWEB-1070]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1363]
**[Christian Schneider](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:1ddb2440-a098-4434-b15c-ca19220b163b)** created **[PAXWEB-1070](https://ops4j1.jira.com/browse/PAXWEB-1070)** 

To reproduce the issue with a simpler example than activemq:

Start karaf 4.1.1-SNAPSHOT<br /> feature:install war<br /> install -s mvn:org.ops4j.pax.web.samples/jsp-filter/6.0.4-SNAPSHOT/war

Open this url in browser:<br /> [http://localhost:8181/jsp-filter/test-taglib-inc.jsp](http://localhost:8181/jsp-filter/test-taglib-inc.jsp)

The source of the html page should contain the "c:" tags. So the core taglib is not included.

—<br /> In the ActiveMQ webconsole all tag libs do not seem to work. I first thought they were simply not defined and added them manually to the jsps.

Only now I found that they are included centrally using thes config below. It seems this config works in karaf 4.0.x but not in karaf 4.1.0. So I think this is an issue in pax web.

```java
  <jsp-config>
    <jsp-property-group>
      <url-pattern>*.jsp</url-pattern>
      <include-prelude>/WEB-INF/jspf/headertags.jspf</include-prelude>
    </jsp-property-group>
  </jsp-config>
```

To reproduce start karaf 4.1.0 then:

feature:repo-add activemq 5.14.3<br /> feature:install activemq-broker

Then use browser to view:<br /> [http://localhost:8181/activemqweb](http://localhost:8181/activemqweb)

The page will show the plain tags. So the tag libs are not active.

---

**Affects:** 6.0.2
**Fixed in:** 6.0.4, 6.1.0
Votes: 0, Watches: 2

**Comment by grgrzybek** [comment]
Works as a charm in Pax Web 8:
```
[INFO] Running org.ops4j.pax.web.itest.jetty.war.jsp.JspFilterIntegrationTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.507 s - in org.ops4j.pax.web.itest.jetty.war.jsp.JspFilterIntegrationTest
```

The filter url pattern was not correct, instead of:
```xml
	<jsp-config>
		<jsp-property-group>
			<url-pattern>test-taglib-inc.jsp</url-pattern>
			<include-prelude>/WEB-INF/jspf/headertags.jspf</include-prelude>
		</jsp-property-group>
	</jsp-config>
```
It should have leading `/`:
```xml
	<jsp-config>
		<jsp-property-group>
			<url-pattern>/test-taglib-inc.jsp</url-pattern>
			<include-prelude>/WEB-INF/jspf/headertags.jspf</include-prelude>
		</jsp-property-group>
	</jsp-config>
```

Anyway - there are lot more improvements in Pax Web 8.

cc: @ANierbeck
