### ISSUE TITLE
ServletContext becomes unavailable on restart when using Whiteboard and CustomContexts [PAXWEB-1077]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1368]
**[Syferlock Support](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:b33c30ad-101b-439d-917d-b664fbd0f28a)** created **[PAXWEB-1077](https://ops4j1.jira.com/browse/PAXWEB-1077)** 

When developing with the whiteboard-extender with or without DS, the HttpContext is lost when stopping and starting the servlet bundle. This prevents the servlet from being accessed again until the entire framework is stopped and started.

Able to show the Pax example whiteboard-ds shows this behavior as well.

Steps to Reproduce:

* install fresh Karaf 4.1.0 and start it
* from Karaf shell:<br /> feature:install pax-http-whiteboard (this is 6.0.2, but 6.0.3 fails as well)<br /> feature:install webconsole

* from Karaf webconsole, install whiteboard-ds-6.0.3-SNAPSHOT.jar (compiled from sources)

* navigate to [http://localhost:8181/context/servlet](http://localhost:8181/context/servlet)

displays "Hello from ServletWithContext" as expected

* from Karaf webconsole or shell, stop and start whiteboard-ds bundle

navigate to [http://localhost:8181/context/servlet](http://localhost:8181/context/servlet) again

receive this:<br /> "HTTP ERROR 404

Problem accessing /context/servlet. Reason:

Not Found"

with this in the logs - the only warning or error that jumped out:

2017-03-14 19:46:34,896 | WARN | qtp289012751-105 | HttpServiceStopped | 98 - org.ops4j.pax.web.pax-web-runtime - 6.0.2 | Http service has already been stopped

---

**Affects:** 6.0.2, 6.0.3
**Fixed in:** 6.1.3, 6.0.13
Votes: 0, Watches: 4

**Comment by grgrzybek** [comment]
In Pax Web 8 I've implemented `org.ops4j.pax.web.itest.container.whiteboard.AbstractWhiteboardDSRestartIntegrationTest` (with Jetty, Tomcat and Undertow versions) that tests all the scenarios, where both pax-web-extender-whiteboard bundle itself is restarted and also the bundle which registers (using SCR) the Whiteboard elements (contexts and servlets/filters/...).
It's working without problems, so marking as _fixed in Pax Web 8_.
