### ISSUE TITLE
Cannot use custom JSP tags and/or custom HttpContexts (with context roots) simultaneously [PAXWEB-1106]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1398]
**[Syferlock Support](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:b33c30ad-101b-439d-917d-b664fbd0f28a)** created **[PAXWEB-1106](https://ops4j1.jira.com/browse/PAXWEB-1106)** 

Related to [https://groups.google.com/forum/#!topic/ops4j/A5kT5EX00K4](https://groups.google.com/forum/#!topic/ops4j/A5kT5EX00K4)

Trying to get custom .tag files working, but the Whiteboard Extender does not seem to like it (this is outside of a WAB/WAR)

I am attaching a single class, Activator.java, which creates all the services, and also has a few flags to reproduce the bug. There are also 2 supporting classes, index.jsp and /WEB-INF/tags/layout.tag to test the custom tag functionality.

If I create a DefaultHttpContext and try to wrap it so that I can handle handleSecurity, then the JSP compiler cannot find the custom tag. If I use my own custom HttpContext/ServletContextHandler, it also fails. Seems like a resource lookup bug.

None of the Whiteboard properties seem to work as intended in this scenario, which seems common: Servlet-&gt;forward to JSP-&gt;access custom .tag (not .tld)

The code attached is currently working, but seems like a workaround - the end goal would be to use OSGI-spec annotations to accomplish the same. Either I am missing something, or there is a bug

---

**Affects:** 6.0.5
**Fixed in:** 6.1.3, 6.0.13
**Attachments:**
* [Activator.java](https://ops4j1.jira.com/secure/attachment/16302/Activator.java)
* [index.jsp](https://ops4j1.jira.com/secure/attachment/16301/index.jsp)
* [layout.tag](https://ops4j1.jira.com/secure/attachment/16300/layout.tag)

Votes: 0, Watches: 2

**Comment by grgrzybek** [comment]
Works in Pax Web 8 - there are many tests involving TLDs and JSF descriptors - both in embedded and wired modes.
