### ISSUE TITLE
HTTP Whiteboard and selection of the ServletContextHelper [PAXWEB-1123]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1413]
**[Jérémie Brébec](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:129b50bc-9459-4fce-a3ba-89a04ce59cb3)** created **[PAXWEB-1123](https://ops4j1.jira.com/browse/PAXWEB-1123)** 

The current implementation of the property "osgi.http.whiteboard.context.select" is not compliant to the R6 Whiteboard specification.

This property is an osgi filter which can match any property of a ServletContextHelper. Moreover, this filter can match multiple ServletContextHelper : In this case, for each ServletContextHelper, the Whiteboard element is instanciated (through ServiceObject) and added to corresponding ServletContext.

From the specification :

> **140.3 Common Whiteboard Properties**
> 
> osgi.http.whiteboard.context.select (optional) :
> An LDAP-style filter to select the associated ServletContextHelper service to use. Any service property of the Servlet Context Helper can be filtered on. If this property is missing the default Servlet Context Helper is used.
> 
> For example, to select a Servlet Context Helper with name myCTX provide the following value:
> (osgi.http.whiteboard.context.name=myCTX)
> 
> To select all Servlet Context Helpers provide the following value:
> (osgi.http.whiteboard.context.name=*)
> If no matching context exists this is reflected in the failure DTOs. See HTTP_WHITEBOARD_CONTEXT_SELECT
> 
> ...
> 
> If multiple Servlet Context Helper services match the osgi.http.whiteboard.context.select property the servlet, filter, resource or listener will be registered with all these Servlet Context Helpers.
> To avoid multiple init() and destroy() calls on the same instance, servlets and filters should be registered as Prototype Service Factory.
> 

---

**Affects:** 6.0.6
**Fixed in:** 8.0.0, 6.1.3, 7.0.1, 6.0.13
Votes: 0, Watches: 1

**Comment by grgrzybek** [comment]
This particular issue was the main reason for me to refactor and eventually almost rewrite Pax Web.

While the original Whiteboard part of Pax Web was created by brilliant devs of Pax Web (not me) _before_ OSGi CMPN Whiteboard specification and while Pax Web was mentioned in OSGi CMPN Whiteboard as the inspiration of this spec, the fact is that Pax Web 7 is simply not compliant to the specification.

The main reason was - CMPN specification allows a Whiteboard servlce/element (like servlet) to be associated with _many_ ServletContextHalper services, Pax Web did only a 1:1 mapping.

This single change was a reason to almost full refactor, but now I believe it's working pretty well in Pax Web 8.

See for example [this test, which registers servlets and filters to many contexts with different rankings](https://github.com/ops4j/org.ops4j.pax.web/blob/338246dd859cc8a078e2063182bfbcbf92d95520/pax-web-itest/pax-web-itest-server/src/test/java/org/ops4j/pax/web/itest/server/whiteboard/WhiteboardContextsTest.java#L251-L275).
