### ISSUE TITLE
HTTP/2 cleartext support [PAXWEB-1130]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1420]
**[Tuomas Kiviaho](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:1b9f7ab9-5a53-423a-bed4-4780828202e5)** created **[PAXWEB-1130](https://ops4j1.jira.com/browse/PAXWEB-1130)** 

I noticed that there is no support for the cleartext alternative that [https://webtide.com/jetty-http2-cleartext-upgrade/](https://webtide.com/jetty-http2-cleartext-upgrade/) describes. [PAXWEB-872](https://ops4j1.jira.com/browse/PAXWEB-872) or [https://github.com/ops4j/org.ops4j.pax.web/commit/b0ac9e4736573b0fbe9936c76264a7afceb6588a#diff-fdc02770af27596b101e786a52326867](https://github.com/ops4j/org.ops4j.pax.web/commit/b0ac9e4736573b0fbe9936c76264a7afceb6588a#diff-fdc02770af27596b101e786a52326867) shows that instead falling back to HTTP 1.1 the server connector could still try this trick

---

**Affects:** 6.0.7
**Fixed in:** 8.0.0, 6.1.3, 7.0.1
Votes: 0, Watches: 1

**Comment by grgrzybek** [comment]
https://github.com/ops4j/org.ops4j.pax.web/commit/e67a0381bc7921d6114ed092b3de6a7ee393dab6 adds verified (integration and unit tests) support for `h2c` in all three runtimes. The only thing left is set of Karaf integration tests to verify features (Jetty is the most problematic here).
