### ISSUE TITLE
Improve pax-web before 8.0.0 release [PAXWEB-1190]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1474]
**[Grzegorz Grzybek](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:9c7cd322-6f60-46ab-9235-bab9ac2f59f6)** created **[PAXWEB-1190](https://ops4j1.jira.com/browse/PAXWEB-1190)** 

I'm going to do a bit of review of pax-web including POM structure, dependency management, coverage, reporting, etc.

---

**Fixed in:** 8.0.0
Votes: 0, Watches: 1

**Comment by grgrzybek** [comment]
I've refactored so many parts of Pax Web at this point that I'm closing this issue. I finally feel comfortable creating separate issues for remaining Pax Web 8 tasks.
The _improvement_ changes include:
* reorganizing POMs and dependencies
* reorganizing samples
* reorganizing integration tests (there are separate JSP tests, non-OSGI tests for server controllers, OSGi generic tests for resource management, etc.)
* unifying as much as possible the layout of pax-web-jetty, pax-web-tomcat and pax-web-undertow
* pax-web-tomcat no longer uses TIPI Tomcat artifacts and Pax Web has much more control on where Tomcat packages are exported from
