### ISSUE TITLE
Reorganize samples [PAXWEB-1192]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1476]
**[Grzegorz Grzybek](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:9c7cd322-6f60-46ab-9235-bab9ac2f59f6)** created **[PAXWEB-1192](https://ops4j1.jira.com/browse/PAXWEB-1192)** 

---

Votes: 0, Watches: 2

**Comment by grgrzybek** [comment]
There are now separate folders for:
* configuration samples (bundle fragments with server configuration resources - undertow.xml, tomcat-server.xml or jetty.xml)
* HttpService/WebContainer samples related to chapter 102 of OSGi CMPN specification
* Internal samples for low level tests
* JSF samples - usually WARs but with JSF dependencies
* JSP samples
* WAR/WAB samples - a lot of them, including new Vaadin ones
* Whiteboard samples
