### ISSUE TITLE
Adjust ServletEvents to carry more precise information [PAXWEB-1253]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1532]
**[Grzegorz Grzybek](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:9c7cd322-6f60-46ab-9235-bab9ac2f59f6)** created **[PAXWEB-1253](https://ops4j1.jira.com/browse/PAXWEB-1253)** 

[https://groups.google.com/forum/#!topic/ops4j/xFAGUSdqcjg](https://groups.google.com/forum/#!topic/ops4j/xFAGUSdqcjg)

In Pax Web 8 (OSGi CMPN R7 implementation) a servlet (any whiteboard *element*) may be associated with multiple *contexts* - it has to be reflected in the servlet event and correctly leveraged in Karaf commands.

After fixing this issue, I'll create related issue in Karaf itself.

---

**Fixed in:** 8.0.0
Votes: 0, Watches: 1

**Comment by grgrzybek** [comment]
All the Whiteboard elements (not only servlets) have this registration information associated with the event. So Karaf will be able to show much more information than with Pax Web 7.
