### ISSUE TITLE
Ensure that we can set up multiple http-listeners in Undertow [PAXWEB-1265]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1544]
**[Grzegorz Grzybek](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:9c7cd322-6f60-46ab-9235-bab9ac2f59f6)** created **[PAXWEB-1265](https://ops4j1.jira.com/browse/PAXWEB-1265)** 

This is a configuration that could be useful for "readiness check" scenario:

```xml
<subsystem xmlns="urn:jboss:domain:undertow:3.1">
    <buffer-cache name="default"/>
    <server name="default-server">
        <http-listener name="default" socket-binding="http" redirect-socket="https"/>
        <http-listener name="health" socket-binding="health" redirect-socket="https"/>
        <host name="default-host" alias="localhost">
            <location name="/" handler="welcome-content"/>
            <filter-ref name="server-header"/>
            <filter-ref name="x-powered-by-header"/>
            <filter-ref name="health-port-filter"/>
        </host>
    </server>
    <filters>
        <expression-filter name="health-port-filter" expression="path-prefix('/health-check') or path-prefix('/readiness-check') and not equals(%p, 9000) -> response-code(404)"/> 
    </filters>
</subsystem>
<socket-binding-group name="standard-sockets" default-interface="public" port-offset="${jboss.socket.binding.port-offset:0}">
    <socket-binding name="http" port="8181"/>
    <socket-binding name="health" port="9000"/>
</socket-binding-group>
```

---

**Fixed in:** 8.0.0
Votes: 0, Watches: 1

**Comment by grgrzybek** [comment]
[All the listeners](https://github.com/ops4j/org.ops4j.pax.web/blob/338246dd859cc8a078e2063182bfbcbf92d95520/pax-web-undertow/src/main/java/org/ops4j/pax/web/service/undertow/internal/UndertowServerWrapper.java#L576-L647) can be configured using external `undertow.xml` file and all are used in the embedded Undertow server.

Pax Web 8 doesn't even use `io.undertow.Undertow` builder class! The server is constructed in a similar way to how Wildfly does it - `org.xnio.XnioWorker#createStreamConnectionServer()` or `io.undertow.protocols.ssl.UndertowXnioSsl#createSslConnectionServer()` are called directly - each listener may have a root handler configured independently.
