### ISSUE TITLE
Jetty 9.4.39 SSLHandshakeException issue causes POST operations to fail with EOF exception.

### ISSUE THREAD

**Issue by pjs102** [ops4j/org.ops4j.pax.web#1600]
There is a bug in SSL implementation of jetty 9.4.39 that causes a SSLHandshakeException when submitting data through post requests.  https://github.com/eclipse/jetty.project/issues/6121  
These exceptions are silently captured and the EOF flag is set, this in turn causes an EOF or Early EOF exception to be thrown when the data is read. 

Please upgrade to jetty to version 9.4.40.v20210413

**Comment by jbonofre** [comment]
Thanks, I'm quickly upgrade and cut new Pax Web releases.

**Comment by jbonofre** [comment]
Updated to Jetty 9.4.40.v20210413 on `pax-web-7.4.x`,  `pax-web-7.3.x`, and `pax-web-7.2.x` branches.
