### ISSUE TITLE
Not possible to set org.ops4j.pax.web.config.files in config

### ISSUE THREAD

**Issue by alienintheheights** [ops4j/org.ops4j.pax.web#1601]
There are two jetty config file params, the single `org.ops4j.pax.web.config.file` and the plural `org.ops4j.pax.web.config.files`. The single is deprecated. I'm working with karaf and am trying to set multiple jetty config files for its pax-web. Namely, I need to set a jetty-web.xml to [override some settings](https://docs.huihoo.com/jetty/the-definitive-reference/override-web-xml.html). I'm able to use the config file org.ops4j.pax.web.cfg to set an alternative `org.ops4j.pax.web.config.file` value, but it ignores any values for `org.ops4j.pax.web.config.files`.

Is there a workaround? Seems like this is a bug.

**Comment by alienintheheights** [comment]
Sorry I see the issue. Looks like the `org.ops4j.pax.web.config.files` config was added after the pax-web version (7.2.14) that's packaged in karaf 4.2.8. I'll try upgrading to karaf 4.2.9 which pulls a newer version. Thanks

**Comment by alienintheheights** [comment]
Ok, I am now pulling the correct version of pax.web and I am still unable to configure the plural form of this config. Is there a Java workaround using Activators, etc? Otherwise we're blocked.

**Comment by alienintheheights** [comment]
Also tried adding a jetty-web.xml in the WEB-INF, which works but the HttpServiceContext doesn't implement all of the methods in WebAppContext, namely overrideDescriptor. It's looking like we'll need to add an Apache front-end to our karaf to do this, which were trying to avoid. 

In summary:
1) Unable to configure multiple jetty files using org.ops4j.pax.web.config.files. It's ignored.
2) Unable to use all of the features available in WebAppContext in jetty-web.xml

**Comment by grgrzybek** [comment]
Hello

Unfortunately there's no `org.ops4j.pax.web.config.files` option at all and
`org.ops4j.pax.web.config.file` is treated only as single value.

In Pax Web 8 I already treat this option as comma-separated value and parse
all configurations:
https://github.com/ops4j/org.ops4j.pax.web/blob/main/pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyServerWrapper.java#L315-L337

So I have no other solution than to ask you to keep fingers crosses, so I
find time to finish Pax Web 8 soon ;)

regards
Grzegorz Grzybek

wt., 27 kwi 2021 o 18:00 Andrew ***@***.***> napisał(a):
