### ISSUE TITLE
Upgrade to javax.annotation 1.3.2

### ISSUE THREAD

**Issue by jbonofre** [ops4j/org.ops4j.pax.web#1642]

**Comment by grgrzybek** [comment]
I've recently updated it in Pax Web 8, because I've finally added tests related to `@ServletSecurity` and `@DeclaresRoles` annotations in #1639

**Comment by jbonofre** [comment]
Good for Pax Web 8, I do it on Pax Web 7.x just to have dependencies aligned with Karaf.
