### ISSUE TITLE
Reimplement Jasypt enc/decryption for configuration entries

### ISSUE THREAD

**Issue by grgrzybek** [ops4j/org.ops4j.pax.web#1655]
Pax Web before 8 had some implementation. I want to reintroduce it.

While there are solutions that process the encrypted Configuration Admin properties on the fly (Felix Fileinstall plugins), Pax Web itself can decrypt some properties as well.

Pax Web 7 only used `org.jasypt.encryption.pbe.StandardPBEStringEncryptor#setPassword()`, but there are better methods:
* `org.jasypt.encryption.pbe.config.EnvironmentPBEConfig#setPasswordEnvName()`
* `org.jasypt.encryption.pbe.config.EnvironmentPBEConfig#setPasswordSysPropertyName()`
* and `org.jasypt.encryption.pbe.config.SimplePBEConfig#setPassword()` too of course.

**Comment by grgrzybek** [comment]
Thanks @oliverlietz for information!
OSGi encryption service is mentioned in #1337. I want to add (back, because it was there in Pax Web 7) pure Jasypt de/encryption support for the compatibility.
The improvement may be that one of:
* `org.ops4j.pax.web.enc.enabled = true`
* `org.ops4j.pax.web.enc.enabled = jasypt`

can use Jasypt encryption and:
* `org.ops4j.pax.web.enc.enabled = osgi`

... wait - I realized there's no such thing as "OSGi encryption service" (a CMPN specification) - it's just tracking of `org.jasypt.encryption.StringEncryptor` OSGi service.

Let me think about it and check Sling.

**Comment by oliverlietz** [comment]
@grgrzybek Yes, I'm not aware of any _OSGi encryption service_ and therefore implemented the module at Sling.

**Comment by grgrzybek** [comment]
@oliverlietz check this out: https://github.com/ops4j/org.ops4j.pax.web/blob/main/pax-web-itest/pax-web-itest-container/pax-web-itest-jetty/src/test/java/org/ops4j/pax/web/itest/jetty/httpservice/WebContainerSecuredWithJasyptServiceIntegrationTest.java

```java
configureAndWaitForServletWithMapping("/helloworld/wc/error/create", () -> {
    hsBundle = installAndStartBundle(sampleURI("wc-helloworld"));
    Dictionary<String, Object> current = config.getProperties();
    if (current == null || !"8443".equals(current.get(PaxWebConfig.PID_CFG_HTTP_PORT_SECURE))) {
        configureAndWaitForListener(8443, () -> {
            config.update(properties);
            StandardPBEStringEncryptor enc = new StandardPBEStringEncryptor();
            EnvironmentStringPBEConfig c = new EnvironmentStringPBEConfig();
            c.setStringOutputType(CommonUtils.STRING_OUTPUT_TYPE_BASE64);
            c.setKeyObtentionIterations(1042);
            c.setAlgorithm("PBEWithHmacSHA256AndAES_256");
            c.setPassword("masterpasswordfortest");
            c.setIvGenerator(new RandomIvGenerator());
            enc.setConfig(c);
            Dictionary<String, Object> props = new Hashtable<>();
            props.put("decryptor", "my-decryptor");
            context.registerService(StringEncryptor.class, enc, props);
        });
    }
});
```
