### ISSUE TITLE
Port HTTP Context processing from Pax Web 7 to Pax Web 8

### ISSUE THREAD

**Issue by grgrzybek** [ops4j/org.ops4j.pax.web#1656]
Pax Web 7 had (since #1453) a way to alter a _context_ created by one bundle using web elements (usually fitlers or security constraints) created in other place (using Configuration Admin).
I want to enable this functionality in Pax Web 8 after the huge refactoring. Probably with some enhancements.

**Comment by precoder** [comment]
We are using pax-web-runtime and pax-web-jetty (which requires pax-web-runtime) together in the OSGI Runtime and Jetty Packages are also provided separately.
Our old version is using Version 7.3.7 but as I can see after this change pax-web-runtime now needs some tomcat dependencies.

Should we add tomcat dependencies into our runtime even if we are not starting tomcat at all or is there another solution for using PAX web only with Jetty?

I can see also from dependencies on internet until 8.0.1 no tomcat required in runtime:
https://mvnrepository.com/artifact/org.ops4j.pax.web/pax-web-runtime/8.0.1

After 8.0.2 tomcat is required:
https://mvnrepository.com/artifact/org.ops4j.pax.web/pax-web-runtime/8.0.2

Here is the Runtime Exception requiring tomcat after switching from 7.3.7 to 9.0.13:

```
ERROR: Bundle org.ops4j.pax.web.pax-web-runtime [80] Error starting file:osgiBundles/pax-web-runtime.jar (org.osgi.framework.BundleException: Unable to resolve org.ops4j.pax.web.pax-web-runtime [80](R 80.0): missing requirement [org.ops4j.pax.web.pax-web-runtime [80](R 80.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.tomcat.util.descriptor.web)(version>=9.0.82)) Unresolved requirements: [[org.ops4j.pax.web.pax-web-runtime [80](R 80.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.tomcat.util.descriptor.web)(version>=9.0.82))])
org.osgi.framework.BundleException: Unable to resolve org.ops4j.pax.web.pax-web-runtime [80](R 80.0): missing requirement [org.ops4j.pax.web.pax-web-runtime [80](R 80.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.tomcat.util.descriptor.web)(version>=9.0.82)) Unresolved requirements: [[org.ops4j.pax.web.pax-web-runtime [80](R 80.0)] osgi.wiring.package; (&(osgi.wiring.package=org.apache.tomcat.util.descriptor.web)(version>=9.0.82))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4398)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:297)
        at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by grgrzybek** [comment]
@precoder different requirement (`org.apache.tomcat.juli`) was relaxed with #1894, but for this problem, you need just one more bundle - [pax-web-tomcat-common](https://repo1.maven.org/maven2/org/ops4j/pax/web/pax-web-tomcat-common/). It's not a full embedded Tomcat server, just several util classes related to `web.xml` parsing and class scanning.

So please install this bundle in your runtime.

**Comment by precoder** [comment]
Thank you very much it works with the new dependency.
