### ISSUE TITLE
Keycloak integration

### ISSUE THREAD

**Issue by grgrzybek** [ops4j/org.ops4j.pax.web#1657]
Pax Web 7 allows Keycloak to configure the runtime (Jetty, Tomcat, Undertow) using bundle fragments with `/META-INF/services/org.ops4j.pax.web.service.AuthenticatorService` service.

Now, after Pax Web was refactored in version 8.0.0, it's time to bring Keycloak back to Pax Web (maybe with little improvements).

**Comment by castortech** [comment]
Is there any info about what was there and what you're looking to accomplish?

We use Keycloak with Paxweb and Jetty and would be very interested, curious if that could be used in our environment.

**Comment by grgrzybek** [comment]
Some time ago, @gnodet has added a "service loader" way for external libraries to get access to the underlying container. It was mostly for Keycloak. I've added ([and described here](https://ops4j1.jira.com/wiki/spaces/paxweb/pages/354025473/HTTP+Context+processing)) a way to alter a _context_ using Configuration Admin.

I simply want to add it back to refactored Pax Web 8.
