### ISSUE TITLE
Basic Auth doesn't work with pax-jetty inside Karaf

### ISSUE THREAD

**Issue by catshout** [ops4j/org.ops4j.pax.web#1697]
I did setup a Karaf 4.3.6 with pax-jetty and did configure the services like as following

etc/jetty.xml (only one entry)
```
    <Call name="addBean">
        <Arg>
            <New class="org.eclipse.jetty.jaas.JAASLoginService">
                <Set name="name">karaf</Set>
                <Set name="loginModuleName">karaf</Set>
                <Set name="roleClassNames">
                    <Array type="java.lang.String">
                        <Item>org.apache.karaf.jaas.boot.principal.RolePrincipal
                        </Item>
                    </Array>
                </Set>
            </New>
        </Arg>
    </Call>
```

etc/org.ops4j.pax.web.context-admin.sample.cfg
```
bundle.symbolicName=sample.xml
login.config.authMethod=BASIC
login.config.realmName=karaf
context.id=default

security.constraint.1.url = /test/*
security.constraint.1.roles = testrole
```

etc/users.prpoperties
```
testuser = passw0rd:testrole
```

deploy/sample.xml
```
<blueprint xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
           xmlns:ext="http://aries.apache.org/blueprint/xmlns/blueprint-ext/v1.0.0"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="
           http://www.osgi.org/xmlns/blueprint/v1.0.0 https://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd">

        <reference id="httpService" interface="org.osgi.service.http.HttpService" />

        <bean id="camelServlet" class="org.apache.camel.component.servlet.CamelHttpTransportServlet"/>

        <bean class="org.apache.camel.component.servlet.osgi.OsgiServletRegisterer"
              init-method="register"
              destroy-method="unregister">
                <property name="servletName" value="servlet1" />
                <property name="alias" value="/test" />
                <property name="httpService" ref="httpService" />
                <property name="servlet" ref="camelServlet" />
        </bean>

    <camelContext id="sample" xmlns="http://camel.apache.org/schema/blueprint">
        <route>
            <from uri="servlet://hello?servletName=servlet1" />
            <log message="Hello Camel!" />
        </route>
    </camelContext>

</blueprint>
```

The following command
```
curl --location --request GET 'http://<hos>:8181/test/hello' \
--header 'Authorization: Basic dGVzdHVzZXI6cGFzc3cwcmQ='
```

produces the following
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 401 Unauthorized</title>
</head>
<body><h2>HTTP ERROR 401 Unauthorized</h2>
<table>
<tr><th>URI:</th><td>/test/hello</td></tr>
<tr><th>STATUS:</th><td>401</td></tr>
<tr><th>MESSAGE:</th><td>Unauthorized</td></tr>
<tr><th>SERVLET:</th><td>servlet1</td></tr>
</table>
<hr><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.43.v20210629</a><hr/>

</body>
</html>
```

I did also install `geronimo-jaspi-2.0.0.jar` into the deploy folder.

Any ideas what might be missing here?

Best
Gerald

**Comment by grgrzybek** [comment]
Before I check in the code, please test with `etc/users.properties` containing:
```
testuser = passw0rd,testrole
```
(change `:` to `,`)

**Comment by catshout** [comment]
@grgrzybek yes, many thanks. The `:` in the group entries was confusing me.

For further, might it be possible to add the `geronimo-jaspi` into the build?

Best
Gerald

**Comment by grgrzybek** [comment]
I'm glad it worked. As about geronimo-jaspi, I'd like to avoid it now before I investigate #1640.
For now Pax Web 8 is the main branch and I'm working to make it 100% implemented (no issues pending) and JSR-196 is one of the topics. I don't use Geronimo bundles at all now.
Please watch #1640 - I'm actually checking the specification and Jetty/Tomcat/Undertow support for it exactly now ;).

**Comment by catshout** [comment]
Ah good to know. Could you roughly predict when the new version of pax-web-jetty would be released to embed into Karaf?

**Comment by grgrzybek** [comment]
Pax Web 8.0.1 is already being incorporated into Karaf (see https://issues.apache.org/jira/browse/KARAF-7392) and Pax Web 7.2.x/7.3.x (Karaf 4.2 and 4.3 respectively) are in kind of _maintenance mode_, so no big changes are coming there.

About this JASPIC/JSR-196 - it's very old specific and not very popular.

Tomcat has quite nice support for it (https://tomcat.apache.org/tomcat-9.0-doc/config/jaspic.html, mentioning https://github.com/phillipgreenii/google-oauth-2.0-serverauthmodule).

Jetty has weird support - all Jetty's implementations of `javax.security.auth.message.module.ServerAuthModule` have been marked as deprecated in 2009...

**Comment by catshout** [comment]
So when will JASPI/JSR196 part of pax-web that we can get rid of `geronimo-jaspi`?

**Comment by grgrzybek** [comment]
For now Pax Web 8.0.1 doesn't user geronimo-jaspi (or even JASPIC in general) at all. I plan to make it optional feature.
In Pax Web 7, it's part of Jetty and Tomcat features and I wouldn't touch it at this stage.

**Comment by catshout** [comment]
Ok, so without `geronimo-jaspi` in place I'm getting

```
Exception in thread "paxweb-context-3-thread-1" java.lang.SecurityException: AuthConfigFactory error: java.lang.ClassNotFoundException: org.apache.geronimo.components.jaspi.AuthConfigFactoryImpl not found by org.apache.geronimo.specs.geronimo-jaspic_1.0_spec [54]
            at javax.security.auth.message.config.AuthConfigFactory.getFactory(AuthConfigFactory.java:77)
            at org.eclipse.jetty.security.jaspi.JaspiAuthenticatorFactory.getAuthenticator(JaspiAuthenticatorFactory.java:90)
            at org.eclipse.jetty.security.SecurityHandler.doStart(SecurityHandler.java:394)
            at org.eclipse.jetty.security.ConstraintSecurityHandler.doStart(ConstraintSecurityHandler.java:417)
...
```

Is there another way to fix this as installing the `geronimo-jaspi` bundle?

**Comment by grgrzybek** [comment]
Yes - because pax web Jetty features contain jetty-jaspi... I've removed it in Pax Web 8...
In Karaf you could blacklist eclipse-jaspi and geronimo-osgi bundles - see https://issues.apache.org/jira/browse/KARAF-5376?focusedCommentId=16431939&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16431939
