### ISSUE TITLE
Pax-web-Jetty causes a Null Pointer Exception if client trust store is not used or defined

### ISSUE THREAD

**Issue by pjs102** [ops4j/org.ops4j.pax.web#1729]
The JettyFactory class in pax-web-jetty attempts to set the TrustStorePath on the sslContextFactory even if client validation is not being used.  This in turn causes sslContext to throw a Null Pointer Exception.  The odd thing is that the next line does a null check on secc.getTruststore().
Please can you tweak the code to only set the sslContextFactory.setTrustStorePath if the truststore is not null.
Thanks
Paul

**Comment by grgrzybek** [comment]
@pjs102 which version of Pax Web do you refer to?

**Comment by pjs102** [comment]
It affects 8.0.4 and the current "main" branch.  
https://github.com/ops4j/org.ops4j.pax.web/blob/main/pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyFactory.java#L300

**Comment by grgrzybek** [comment]
Thanks for reporting - I'll have a look tomorrow.
