### ISSUE TITLE
Cleanup Pax Web features repository

### ISSUE THREAD

**Issue by jbonofre** [ops4j/org.ops4j.pax.web#1737]
Pax Web Karaf features repository XML should be improved with:
- remove <repository/> tag
- don't use specific karaf version (just karaf feature name)

The purpose is to allow users to set their version (at build time or runtime).

**Comment by jbonofre** [comment]
1. It's not only for Pax Web 8.x, but also Pax Web 7.3.x (so Karaf 4.3.x)
2. It's not a good idea to depend to a specific karaf version in a bundle (even with dependency=true), I think it's better to depend to the `shell` feature (just name)

I'm creating a PR as proposal.

**Comment by grgrzybek** [comment]
I think I had problems validating the features when depending on `shell` features instead of the two bundles, but it's definitely a better idea.

**Comment by grgrzybek** [comment]
#1738 merged.
