### ISSUE TITLE
Question: Alternative for ResourceDelegatingBundleClassLoader

### ISSUE THREAD

**Issue by dsteegen** [ops4j/org.ops4j.pax.web#1739]
Hi,

I am upgrading the pax-web dependency in my project from 7.3.7 to 8.0.5 but noticed that the interface ResourceDelegatingBundleClassLoader does not exist anymore. I could not find immediately an alternative for this SPI interface so I am wondering if you guys could help me out with this.
Thank you!

**Comment by grgrzybek** [comment]
Pax Web 7's `org.ops4j.pax.web.service.spi.util.ResourceDelegatingBundleClassLoader` was effectively replaced by `org.ops4j.pax.web.service.spi.servlet.OsgiServletContextClassLoader` in Pax Web 8.

It's now more of an internal classLoader that collects visible/reachable bundles during WAB processing, but it's used in unified way also in Whiteboard and HttpService scenarios.

Pax Web 8 no longer needs XBean and Swissbox (and in Pax Web 7 this ResourceDelegating CL extended `org.ops4j.pax.swissbox.core.BundleClassLoader`).

There should be no problem for you to switch to `org.ops4j.pax.web.service.spi.servlet.OsgiServletContextClassLoader`, but I can help verifying/checking your use case - maybe this classloader isn't needed at all?

**Comment by dsteegen** [comment]
@grgrzybek 

I found the `OsgiServletContextClassLoader` myself after digging a little further. It does exactly what we need so I could just use it as a drop-in replacement for the  `ResourceDelegatingBundleClassLoader` class.
Thank you for the help! I will close this issue as my question was answered.

**Comment by grgrzybek** [comment]
you/re welcome ;)
