### ISSUE TITLE
[8.0.x] pax-web jetty runtime bundle

### ISSUE THREAD

**Issue by rimmeraj** [ops4j/org.ops4j.pax.web#1755]
I am trying to use the org.ops4j.pax.web.pax-web-jetty-bundle , which I am assuming means I should not need the org.ops4j.pax.web.pax-web-runtime bundle and all of the tomcat requirements. However we are missing the 

Provide-Capability                      osgi.implementation;osgi.implementation="osgi.http";

manifest entry and thus I am still pulling in the org.ops4j.pax.web.pax-web-runtime bundle

**Comment by grgrzybek** [comment]
Looks like a bug - I didn't verify all the req/cap headers for contracts, services and implementations. Thanks for report - I should fix it quickly and release 8.0.8 next week.
Please specify the version you use.

**Comment by rimmeraj** [comment]
I was testing the latest. I will try 8.0.8 once you have released it
