### ISSUE TITLE
currentThread.contextClassLoader does not include the Servlet bundle using http whiteboard.

### ISSUE THREAD

**Issue by qianwch** [ops4j/org.ops4j.pax.web#1759]
Registering the servlet to http whiteboard:
```java
    Dictionary<String, String> props = new Hashtable<>();
    props.put(HTTP_WHITEBOARD_SERVLET_PATTERN, "/hello");
    props.put(HTTP_WHITEBOARD_SERVLET_NAME, "helloservlet");
    props.put(HTTP_WHITEBOARD_SERVLET_ASYNC_SUPPORTED, "true");
    props.put(HTTP_WHITEBOARD_CONTEXT_SELECT,
      String.format("(osgi.http.whiteboard.context.name=%s)",
        "default"));
    context.registerService(Servlet.class, new MyServlet(), props);
```
The following code will get an exception.
```java
public class MyServlet extends HttpServlet {

	public void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		response.getWriter().println("<h1>it worked</h1>");
		try {
			Thread.currentThread().getContextClassLoader().loadClass(MyServlet.class.getName());
		} catch (ClassNotFoundException e) {
			throw new RuntimeException(e);
		}
	}

	public void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// your logic here
	}

}

```
The demo project is here.
[demo.zip](https://github.com/ops4j/org.ops4j.pax.web/files/9562012/demo.zip)

**Comment by grgrzybek** [comment]
@qianwch which version of Pax web? I can't see it from your project...

**Comment by qianwch** [comment]
> 

The test was run in Karaf 4.4.1 which using pax web 8.0.6, and I have manually upgrade it to 8.0.8, the same problem.

**Comment by grgrzybek** [comment]
Got it - did you check with all runtimes? Or only, say, Jetty?

**Comment by qianwch** [comment]
> 

I have tested it with jetty/tomcat/undertow.

**Comment by grgrzybek** [comment]
Thanks for report - it is indeed a problem which I never noticed...
The TCCL is set by Pax Web but it doesn't include your bundle:
```
result = {org.ops4j.pax.web.service.spi.servlet.OsgiServletContextClassLoader@8322} 
 bundles: java.util.List  = {java.util.Collections$UnmodifiableRandomAccessList@8330}  size = 2
  0 = {org.apache.felix.framework.BundleImpl@8344} "org.ops4j.pax.web.pax-web-extender-whiteboard [70]"
  1 = {org.apache.felix.framework.BundleImpl@8345} "org.ops4j.pax.web.pax-web-jetty [71]"
```

**Comment by grgrzybek** [comment]
The point is that Whiteboard specification, Http Service specification and Web Applications specification from OSGi CMPN say nothing about TCCL.

If you (in your servlet) get the servlet context and a classloader from it, you'd get a classloader that can load your class.
`req.getServletContext().getClassLoader()` returns:
```
result = {org.apache.felix.framework.BundleWiringImpl$BundleClassLoader@7778} "cn.qian.osgi.demo-pax1 [76]"
```

See https://docs.osgi.org/specification/osgi.cmpn/7.0.0/service.http.whiteboard.html#d0e119708:
> `getClassLoader()` […] Returns the class loader of the bundle that registered the Whiteboard service. An implementation of this specification can achieve this by returning separate façades of the ServletContext to each Whiteboard service. Each façade accesses the Whiteboard service's Bundle Wiring to obtain its class loader. 

Servlet API 4.0 specification says in `10.7.2 Web Application Class Loader`:
> An implementation MUST also guarantee that for every web application deployed in a container, a call to Thread.currentThread.getContextClassLoader() MUST return a ClassLoader instance that implements the contract specified in this section.  Furthermore, the ClassLoader instance MUST be a separate instance for each deployed web application. The container is required to set the thread context ClassLoader as described above before making any callbacks (including listener callbacks) into the web application, and set it back to the original ClassLoader, once the callback returns.

For WARs/WABs, I've installed `mvn:org.ops4j.pax.web.samples/war-simplest-osgi/8.0.6/war` and both:
* `req.getServletContext().getClassLoader()`
* `Thread.currentThread().getContextClassLoader()`

return **the same** class loader with:
```
result = {org.ops4j.pax.web.service.spi.servlet.OsgiServletContextClassLoader@8211} 
 assertionLock: java.lang.Object  = {org.ops4j.pax.web.service.spi.servlet.OsgiServletContextClassLoader@8211} 
 bundles: java.util.List  = {java.util.Collections$UnmodifiableRandomAccessList@8219}  size = 3
  0 = {org.apache.felix.framework.BundleImpl@8233} "org.ops4j.pax.web.samples.war-simplest-osgi [80]"
  1 = {org.apache.felix.framework.BundleImpl@8234} "org.ops4j.pax.web.pax-web-tomcat-common [75]"
  2 = {org.apache.felix.framework.BundleImpl@8235} "org.ops4j.pax.web.pax-web-jetty [71]"
```

**Comment by qianwch** [comment]
Yes I have tested wab, it is fine. But for whiteboard, it is not.
Servlet containers will set context class loader for request processing thread to ServletContext.getClassLoader().In whiteboard case, it is expected to set the context class loader to the OsgiScopedServletContext.getClassLoader(), but it is not currently.

**Comment by grgrzybek** [comment]
> In whiteboard case, it is expected to set the context class loader to the OsgiScopedServletContext.getClassLoader(), but it is not currently.
yes - by the rule of "least surprise". But it's not explicit in OSGi CMPN specification(s).

I have a fix almost ready (tests pending).

**Comment by grgrzybek** [comment]
Done - thank you very much @qianwch for spotting this. I didn't add new tests, but I've added:
```java
Thread.currentThread().getContextClassLoader().loadClass(this.getClass().getName())
```

in several sample methods for servlets, listeners, filters and websockets - all these had the same problem.
Now the TCCL is a ClassLoader that _sees_ the bundle for given web element.

**Comment by qianwch** [comment]
I have tested version 8.0.9. Still has problem.
1. TCCL now includes the servlet bundle. But the TCCL is not the same as servletContext.getClassLoader()
2. Even worse, TCCL includes every servlet bundles, so the class space collides between the servlet bundles. easily get class cast exceptions.
Here are the two bundles that will demo the class space collision problem:
[demo1.zip](https://github.com/ops4j/org.ops4j.pax.web/files/9580539/demo1.zip)
[demo2.zip](https://github.com/ops4j/org.ops4j.pax.web/files/9580540/demo2.zip)

And it is the TCCL:
<img width="648" alt="截屏2022-09-16 11 54 16" src="https://user-images.githubusercontent.com/45196316/190553160-bdda4dfe-23e3-4919-8243-39e71cb4faec.png">
