### ISSUE TITLE
Question - Jetty with multiple SSL transports?

### ISSUE THREAD

**Issue by mattrpav** [ops4j/org.ops4j.pax.web#1791]
Is it possible to configure pax-web (jetty) with multiple SSL transports using different keystores?

**Comment by grgrzybek** [comment]
@mattrpav definitely not using pure `org.ops4j.pax.web` PID (and its `org.ops4j.pax.web.ssl.*` properties), but it should be doable by configuring the SSL connectors in native configuration files (`etc/jetty.xml`, `etc/tomcat-server.xml` and `etc/undertow.xml`).

**Comment by Maurice-Betzel** [comment]
Something like this:
pax.web.cfg

org.ops4j.pax.web.listening.addresses=0.0.0.0
org.osgi.service.http.enabled=true
org.osgi.service.http.port=80
org.osgi.service.http.secure.enabled=true
org.osgi.service.http.port.secure=443
org.ops4j.pax.web.config.file=${karaf.etc}/jetty.xml

jetty.xml

<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_0.dtd">

<Configure id="Server" class="org.eclipse.jetty.server.Server">

	
	
	

	<New id="httpConfig" class="org.eclipse.jetty.server.HttpConfiguration">
		<Set name="securePort">443</Set>
		<Set name="secureScheme">https</Set>
		<Set name="headerCacheSize">4096</Set>
		<Set name="sendXPoweredBy">false</Set>
		<Set name="sendDateHeader">false</Set>
		<Set name="sendServerVersion">false</Set>		
	</New>
	
	<New id="httpsConfig" class="org.eclipse.jetty.server.HttpConfiguration">
            <Arg>
                <Ref refid="httpConfig"/>
            </Arg>
            <Call name="addCustomizer">
			<Arg>
				<New class="org.eclipse.jetty.server.SecureRequestCustomizer">
					<Set name="sniHostCheck" type="boolean">true</Set>
					<Set name="stsMaxAge" type="long">31536000</Set>
					<Set name="stsIncludeSubDomains" type="boolean">true</Set>
				</New>
			</Arg>
		</Call>
    </New>
	
	
	
	
	
	<Get name="handler">
		<Call name="addHandler">
			<Arg>
				<New class="org.eclipse.jetty.server.handler.SecuredRedirectHandler"/>
			</Arg>
		</Call>
	</Get>
	

	
	
	
	
	
	<Call name="addBean">
		<Arg>
			<New class="org.eclipse.jetty.jaas.JAASLoginService">
				<Set name="name">karaf</Set>
				<Set name="loginModuleName">karaf</Set>
				<Set name="roleClassNames">
					<Array type="java.lang.String">
						<Item>org.apache.karaf.jaas.boot.principal.RolePrincipal</Item>
					</Array>
				</Set>
			</New>
		</Arg>
	</Call>
	<Call name="addBean">
		<Arg>
			<New class="org.eclipse.jetty.jaas.JAASLoginService">
				<Set name="name">default</Set>
				<Set name="loginModuleName">karaf</Set>
				<Set name="roleClassNames">
					<Array type="java.lang.String">
						<Item>org.apache.karaf.jaas.boot.principal.RolePrincipal</Item>
					</Array>
				</Set>
			</New>
		</Arg>
	</Call>

	<New id="lansslContextFactory" class="org.eclipse.jetty.util.ssl.SslContextFactory">
		<Set name="KeyStorePath">
			<SystemProperty name="karaf.home"/>/etc/keystore/yyy.p12
		</Set>
		<Set name="KeyStorePassword">YYY</Set>
		<Set name="KeyManagerPassword">YYY</Set>
		<Set name="EndpointIdentificationAlgorithm"/>
		<Set name="NeedClientAuth">
			<Property name="jetty.ssl.needClientAuth" default="false"/>
		</Set>
		<Set name="WantClientAuth">
			<Property name="jetty.ssl.wantClientAuth" default="false"/>
		</Set>
		
		<Set name="ExcludeProtocols">
			<Array type="java.lang.String">
				<Item>SSLv3</Item>
			</Array>
		</Set>
	</New>

	<New id="wansslContextFactory" class="org.eclipse.jetty.util.ssl.SslContextFactory">
		<Set name="KeyStorePath">
			<SystemProperty name="karaf.home"/>/etc/keystore/xxx.jks
		</Set>
		<Set name="KeyStorePassword">XXX</Set>
		<Set name="KeyManagerPassword">XXX</Set>
		<Set name="EndpointIdentificationAlgorithm"/>
		<Set name="NeedClientAuth">
			<Property name="jetty.ssl.needClientAuth" default="false"/>
		</Set>
		<Set name="WantClientAuth">
			<Property name="jetty.ssl.wantClientAuth" default="false"/>
		</Set>
		
		<Set name="ExcludeProtocols">
			<Array type="java.lang.String">
				<Item>SSLv3</Item>
			</Array>
		</Set>
		<Set name="ExcludeCipherSuites">
			<Array type="String">
				<Item>SSL_RSA_WITH_DES_CBC_SHA</Item>
				<Item>SSL_DHE_RSA_WITH_DES_CBC_SHA</Item>
				<Item>SSL_DHE_DSS_WITH_DES_CBC_SHA</Item>
				..add more...
			</Array>
		</Set>
	</New>

	<Call id="lanhttpsConnector" name="addConnector">
		<Arg>
			<New class="org.eclipse.jetty.server.ServerConnector">
				<Arg name="server">
					<Ref refid="Server" />
				</Arg>
				<Arg name="acceptors" type="int">
					<Property name="ssl.acceptors" default="-1"/>
				</Arg>
				<Arg name="selectors" type="int">
					<Property name="ssl.selectors" default="-1"/>
				</Arg>
				<Arg name="factories">
					<Array type="org.eclipse.jetty.server.ConnectionFactory">
						<Item>
							<New class="org.eclipse.jetty.server.SslConnectionFactory">
								<Arg name="next">http/1.1</Arg>
								<Arg name="sslContextFactory">
									<Ref refid="lansslContextFactory"/>
								</Arg>
							</New>
						</Item>
						<Item>
							<New class="org.eclipse.jetty.server.HttpConnectionFactory">
								<Arg name="config">
									<Ref refid="httpsConfig"/>
								</Arg>
							</New>
						</Item>
					</Array>
				</Arg>
				<Set name="name">0.0.0.0:8443</Set>
				<Set name="host">
					<Property name="jetty.host" default="0.0.0.0"/>
				</Set>
				<Set name="port">
					<Property name="https.port" default="8443"/>
				</Set>
				<Set name="idleTimeout">
					<Property name="https.timeout" default="14400000"/>
				</Set>
				<Set name="acceptorPriorityDelta">
					<Property name="ssl.acceptorPriorityDelta" default="0"/>
				</Set>
				<Set name="acceptQueueSize">
					<Property name="https.acceptQueueSize" default="0"/>
				</Set>
			</New>
		</Arg>
	</Call>

	<Call id="wanhttpsConnector" name="addConnector">
		<Arg>
			<New class="org.eclipse.jetty.server.ServerConnector">
				<Arg name="server">
					<Ref refid="Server" />
				</Arg>
				<Arg name="acceptors" type="int">
					<Property name="ssl.acceptors" default="-1"/>
				</Arg>
				<Arg name="selectors" type="int">
					<Property name="ssl.selectors" default="-1"/>
				</Arg>
				<Arg name="factories">
					<Array type="org.eclipse.jetty.server.ConnectionFactory">
						<Item>
							<New class="org.eclipse.jetty.server.SslConnectionFactory">
								<Arg name="next">http/1.1</Arg>
								<Arg name="sslContextFactory">
									<Ref refid="wansslContextFactory"/>
								</Arg>
							</New>
						</Item>
						<Item>
							<New class="org.eclipse.jetty.server.HttpConnectionFactory">
								<Arg name="config">
									<Ref refid="httpsConfig"/>
								</Arg>
							</New>
						</Item>
					</Array>
				</Arg>
				<Set name="name">0.0.0.0:443</Set>
				<Set name="host">
					<Property name="jetty.host" default="0.0.0.0"/>
				</Set>
				<Set name="port">
					<Property name="https.port" default="443"/>
				</Set>
				<Set name="idleTimeout">
					<Property name="https.timeout" default="30000"/>
				</Set>
				<Set name="acceptorPriorityDelta">
					<Property name="ssl.acceptorPriorityDelta" default="0"/>
				</Set>
				<Set name="acceptQueueSize">
					<Property name="https.acceptQueueSize" default="0"/>
				</Set>
			</New>
		</Arg>
	</Call>

	<Call id="wanhttpConnector" name="addConnector">
		<Arg>
			<New id="httpConnector" class="org.eclipse.jetty.server.ServerConnector">
				<Arg name="server">
					<Ref refid="Server" />
				</Arg>
				<Arg name="acceptors" type="int">
					<Property name="jetty.http.acceptors" deprecated="http.acceptors" default="-1"/>
				</Arg>
				<Arg name="selectors" type="int">
					<Property name="jetty.http.selectors" deprecated="http.selectors" default="-1"/>
				</Arg>
				<Arg name="factories">
					<Array type="org.eclipse.jetty.server.ConnectionFactory">
						<Item>
							<New class="org.eclipse.jetty.server.HttpConnectionFactory">
								<Arg name="config">
									<Ref refid="httpConfig" />
								</Arg>
							</New>
						</Item>
					</Array>
				</Arg>
				<Set name="name">0.0.0.0:80</Set>
				<Set name="host">
					<Property name="jetty.http.host" deprecated="jetty.host" default="0.0.0.0"/>
				</Set>
				<Set name="port">
					<Property name="jetty.http.port" deprecated="jetty.port" default="80"/>
				</Set>
				<Set name="idleTimeout">
					<Property name="jetty.http.idleTimeout" deprecated="http.timeout" default="30000"/>
				</Set>
				<Set name="acceptorPriorityDelta">
					<Property name="jetty.http.acceptorPriorityDelta" deprecated="http.acceptorPriorityDelta" default="0"/>
				</Set>
				<Set name="acceptQueueSize">
					<Property name="jetty.http.acceptQueueSize" deprecated="http.acceptQueueSize" default="0"/>
				</Set>
			</New>
		</Arg>
	</Call>

</Configure>

**Comment by mattrpav** [comment]
@grgrzybek @Maurice-Betzel thank you!
