### ISSUE TITLE
[8.0.x] 'Bundle, BundleContext or BundleWiring is null' Exceptions

### ISSUE THREAD

**Issue by olfuerniss** [ops4j/org.ops4j.pax.web#1800]
Hi Grzegorz,

ugraded from Karaf 4.3.7 (pax-web 7.3.25) to Karaf 4.4.2 (pax-web 8.0.11) and since then I see "Bundle, BundleContext or BundleWiring is null" IllegalArgumentExceptions in the logs (see attached [karaf.log](https://github.com/ops4j/org.ops4j.pax.web/files/10054971/karaf.log) file).

It happens every time I deploy a new version of a bundle (copy it to the `[karaf]/deploy` folder). But of course this exception gets not thrown for all bundles. ;-)

The case when it happens all the time:

I have a frontend bundle with a JSP that has some `Import-Package` statements (`MANIFEST.MF`) to packages of the backend bundle that gets deployed.

So when the updated backend bundle gets copied to the `[karaf]/deploy` folder, Karaf (Felix File Install) uninstalls the current bundle and installs the new one.

Due to the dependency of the frontend bundle to packages of the backend bundle. pax-web does some "voodoo" and the `PaxWebTldScanner` scans the frontend bundle for TLD's and in the same step it scans also the dependend backend bundle ("transitive closure of reachable bundles"). 

Then the following code of `org.ops4j.pax.web.utils.ClassPathUtil` throws the exception : 

```
public static Set<Bundle> getBundlesInClassSpace(Bundle bundle, Set<Bundle> bundleSet) {
	BundleWiring bundleWiring = bundle == null ? null : bundle.adapt(BundleWiring.class);

	if (bundle == null || bundleWiring == null) {
		throw new IllegalArgumentException("Bundle, BundleContext or BundleWiring is null");	
	}
```

The given backend "bundle", that gets just re-installed, is in state 2 (= Bundle.INSTALLED). This also means that no BundleWiring adaption is possible for this state at the moment (which is correct) and it throws the IAE. Btw. the backend bundle starts within 3 seconds, in case it is a timing problem.

Not sure if this happens now due to Karaf, Felix File Install or pax-web changes between the above mentioned versions. 

Another problem is that the backend bundle does not always start successfully and goes in state "Resolved" (happened only 2 times within the last 2 weeks). Hopefully this is related, because `log:exception-display` or `bundle:diag` (can't remember) shows then the exception of this ticket.

All the best,
 Oliver

P.S.1: In the attached [karaf.log](https://github.com/ops4j/org.ops4j.pax.web/files/10054971/karaf.log): the mentioned frontend bundle = `bpc-fe-core` and the backend bundle = `bpc-be-core`
P.S.2: The "BundleContext" could be removed from the thrown exception message, the check was removed some time ago and the message not adjusted

**Comment by grgrzybek** [comment]
Thanks for the report. Looks like your analysis is correct. And simple `return Collections.emptySet()` should be used if the bundle is not in `RESOLVED` state, but give me a bit of time to check the impact ;)

And the scenario you've described is typical OSGi one - the bundle is being restarted because there's an uninstall/install performed which leads to refresh. Pax Web reacts to bundle change, but it should (and it's not hard to ensure it) wait for stable (RESOLVED) state skipping STARTING one.

**Comment by grgrzybek** [comment]
@olfuerniss I tried reproducing with simple war→jar relation simulating quick refreshes, but I couldn't reproduce...

Is there a chance you build your own pax-web-api from 8.0.11 tag with this check changed to:
```java
if (bundle == null || bundleWiring == null) {
	return Collections.emptySet();
}
```
and see how it works?

**Comment by olfuerniss** [comment]
@grgrzybek Give me some time ... maven downloads the internet ...

**Comment by grgrzybek** [comment]
thanks!

**Comment by olfuerniss** [comment]
Done. The exception is of course gone now, but the other problem happens now immediately when I copy the backend bundle (bpc-be-core.jar) to the deploy-folder. It tries to reinstall it, stops the dependend frontend bundle (bpc-fe-core.war) and hangs now forever in this state. I'm not even able to stop Karaf by pressing Strg+D.

```
233 │ Active    │  90 │ 4.1.0.SNAPSHOT     │ Dashboard (Frontend)
234 │ Stopping  │  90 │ 4.1.0.SNAPSHOT     │ Core (Frontend)
235 │ Active    │  90 │ 4.1.0.SNAPSHOT     │ Monitor (Backend)
236 │ Active    │  90 │ 4.1.0.SNAPSHOT     │ Analysis (Frontend)
237 │ Installed │  90 │ 4.1.0.SNAPSHOT     │ Core (Backend)
238 │ Resolved  │  90 │ 4.1.0.SNAPSHOT     │ Analysis (Backend)
239 │ Active    │  90 │ 4.1.0.SNAPSHOT     │ Monitor (Frontend)
```

**Comment by grgrzybek** [comment]
Thanks for checking!
Is there a chance you share your project somehow? And describe what you're installing as feature, what as a bundle (`install mvn:xxx`) and what as a copy to `deploy/` directory?

**Comment by olfuerniss** [comment]
I try to break it down.

**Comment by olfuerniss** [comment]
In the backend bundle, I use Blueprint/CXF to register some JAXRS servers and in the BundleActivator.start() I use the HttpService to register a WebSocketServlet and a io.prometheus.client.exporter.MetricsServlet.

Just tested it again (with your fix from above), and it hangs reproducible (Core Backend in state installed forever). Took a thread dump by using IntelliJ IDEA and it seems there is a deadlock (dump attached).

![image](https://user-images.githubusercontent.com/30932609/203913677-19884a45-7d73-488e-8331-8da1ab6aadbe.png)

![image](https://user-images.githubusercontent.com/30932609/203913844-887da5b7-1f27-40b4-94a1-be524893de31.png)

The related code from OsgiServletContextClassLoader
![image](https://user-images.githubusercontent.com/30932609/203914192-9812a473-f991-45a7-8642-24a028c32772.png)


Maybe this helps already. If not, please let me know. I would try to create 2 bundles doing the same but without all the other stuff around.

Attachment: [threads_report.txt](https://github.com/ops4j/org.ops4j.pax.web/files/10089138/threads_report.txt)

**Comment by olfuerniss** [comment]
Some more infos. For the test above I've deployed only the backend and frontend bundle. No additional bundles were deployed at the time to exclude other circumstances.

When the backend bundle with the servlets is the only one deployed (no frontend bundle), there are no problems at all on re-deployment of it. 

But when I deploy also the frontend bundle with the JSP it will deadlock again on deployment of the backend bundle.

**Comment by grgrzybek** [comment]
@olfuerniss, the thread report is super handy - there were lot of deadlocks during my work on Pax Web 8, but there's no chance I fixed them all.
Your analysis is great too and should help. May I ask one more thing? Please set `DEBUG` logging for `org.ops4j.pax.web` logger and (if possible, after cleaning sensitive data) please attach the log. I'd then need nothing more ;)

**Comment by olfuerniss** [comment]
Here is the [karaf.log](https://github.com/ops4j/org.ops4j.pax.web/files/10089485/karaf.log) file. 

Deleted it, started Karaf and have done a re-deployment of the backend bundle at ~08:24:00.

The state of the two bundles afterwards:
```
237 │ Installed │  90 │ 4.1.0.SNAPSHOT     │ Core (Backend)
245 │ Stopping  │  90 │ 4.1.0.SNAPSHOT     │ Core (Frontend)
```

**Comment by grgrzybek** [comment]
thanks! is it for original pax-web 8.0.11 or the one with my suggested change? (empty set instead of an exception).

**Comment by olfuerniss** [comment]
It is the one with 

```
if (bundle == null || bundleWiring == null) {
	return Collections.emptySet();
}
```

**Comment by grgrzybek** [comment]
I'm analyzing the first log now, there's nice order of operations:

1. pax-web-runtime and pax-web-jetty start, which lead to registration of `HttpService`
2. it's handed to `org.apache.karaf.http.core` bundle
3. it's handed to `org.apache.cxf.cxf-rt-transports-http` bundle
4. it's handed to `org.ops4j.pax.web.pax-web-extender-war` bundle
5. it's handed to `org.apache.karaf.web.core` bundle
6. '/' context is first initialized when `org.apache.cxf.cxf-rt-transports-http` registers `/cxf` servlet
7. `HttpService` is handed to `de.virtimo.bpc.bpc-be-core` bundle
8. it registers `/websocket` servlet into `/` (the same context as for `/cxf`)
9. it registers `/metrics` servlet into `/`
10. `de.virtimo.bpc.bpc-fe-core` bundle (WAB) registers `/` web application - because of the improvements in Pax Web 8 it should peacefully exist with previously registered web elements (under common `/` context)
11. the WAB has only `default` (`/`) and `jsp` (`*.jspx`, `*.jsp`) servlets
12. context `/` is restarted
13. TLDs are searched in `pax-web-jsp`
14. TLDs are searched in `de.virtimo.bpc.bpc-fe-core` - **please remove /WEB-INF/lib/jstl-1.2.jar from your WAB!** - jstl library is included in pax-web-jsp
15. `HttpService` is handed to `org.eclipse.jetty.websocket.javax.websocket.server` and `org.eclipse.jetty.websocket.jsr356.server.deploy.WebSocketServerContainerInitializer$ContextDestroyListener` listener is registered
16. `de.virtimo.bpc.bpc-be-core` bundle is updated (in `deploy/` directory)
17. `/metrics` and `/websocket` servlets are unregistered from `/`
18. `HttpService` is untracked from `de.virtimo.bpc.bpc-be-core`
19. `default` and `de.virtimo.bpc.core.BasicAuthHttpContext` HttpContexts are removed from `/` servlet context
20. `/` is started again
21. `FelixFrameworkWiring` thread is restarting `de.virtimo.bpc.bpc-fe-core` WAB while at the same time, `/` context continues its initialization/start

whew - I think I got it - thanks again for the logs, I'll try to prepare a reproducer in Pax Web samples.

**Comment by grgrzybek** [comment]
I got it.

The thread that updates a bundle (after it called BundleActivator.stop()):
```
"pipe-update 84@11116" prio=5 tid=0x375 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.apache.felix.framework.Felix.updateBundle(Felix.java:2650)
	  at org.apache.felix.framework.BundleImpl.update(BundleImpl.java:1026)
	  at org.apache.felix.framework.BundleImpl.update(BundleImpl.java:1012)
	  at org.apache.karaf.bundle.command.Update.doExecute(Update.java:57)
	  at org.apache.karaf.bundle.command.BundleCommand.execute(BundleCommand.java:49)
	  at org.apache.karaf.shell.impl.action.command.ActionCommand.execute(ActionCommand.java:84)
	  at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:68)
	  at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:86)
	  at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:599)
	  at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:526)
	  at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:415)
	  at org.apache.felix.gogo.runtime.Pipe.doCall(Pipe.java:416)
	  at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:229)
	  at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:59)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	  at java.lang.Thread.run(Thread.java:750)
```

The thread that restarts `/` context:
```
"paxweb-config-1-thread-1@10192" prio=5 tid=0x105 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.ops4j.pax.web.utils.ClassPathUtil.getBundlesInClassSpace(ClassPathUtil.java:254)
	  at org.ops4j.pax.web.utils.ClassPathUtil.getBundlesInClassSpace(ClassPathUtil.java:304)
	  at org.ops4j.pax.web.jsp.PaxWebTldScanner.scanBundle(PaxWebTldScanner.java:172)
	  at org.ops4j.pax.web.jsp.PaxWebTldScanner.scan(PaxWebTldScanner.java:91)
	  at org.apache.jasper.servlet.JasperInitializer.onStartup(JasperInitializer.java:83)
	  at org.ops4j.pax.web.jsp.JasperInitializer.onStartup(JasperInitializer.java:141)
	  at org.ops4j.pax.web.service.spi.servlet.SCIWrapper.onStartup(SCIWrapper.java:43)
	  at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.lambda$startContext$1(PaxWebServletContextHandler.java:257)
	  at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler$$Lambda$571.1050556888.accept(Unknown Source:-1)
	  at java.lang.Iterable.forEach(Iterable.java:75)
	  at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.startContext(PaxWebServletContextHandler.java:251)
	  at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916)
	  at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
	  at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.doStart(PaxWebServletContextHandler.java:307)
	  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	  - locked <0x2bee> (a java.lang.Object)
	  at org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper.ensureServletContextStarted(JettyServerWrapper.java:2380)
	  at org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper.visitTransactionStateChange(JettyServerWrapper.java:731)
	  at org.ops4j.pax.web.service.spi.task.TransactionStateChange.accept(TransactionStateChange.java:35)
	  at org.ops4j.pax.web.service.spi.task.Batch.accept(Batch.java:430)
	  at org.ops4j.pax.web.service.jetty.internal.JettyServerController.sendBatch(JettyServerController.java:168)
	  at org.ops4j.pax.web.service.internal.HttpServiceEnabled.lambda$stop$0(HttpServiceEnabled.java:266)
	  at org.ops4j.pax.web.service.internal.HttpServiceEnabled$$Lambda$523.1355082247.run(Unknown Source:-1)
	  at org.ops4j.pax.web.service.spi.model.ServerModel.lambda$run$2(ServerModel.java:540)
	  at org.ops4j.pax.web.service.spi.model.ServerModel$$Lambda$524.1635829942.get(Unknown Source:-1)
	  at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	  at java.lang.Thread.run(Thread.java:750)
```

**Comment by grgrzybek** [comment]
Is it possible you try with this diff?
```
diff --git a/pax-web-api/src/main/java/org/ops4j/pax/web/utils/ClassPathUtil.java b/pax-web-api/src/main/java/org/ops4j/pax/web/utils/ClassPathUtil.java
index b4f84191c..c0808f62b 100644
--- a/pax-web-api/src/main/java/org/ops4j/pax/web/utils/ClassPathUtil.java
+++ b/pax-web-api/src/main/java/org/ops4j/pax/web/utils/ClassPathUtil.java
@@ -251,7 +251,7 @@ public class ClassPathUtil {
 		BundleWiring bundleWiring = bundle == null ? null : bundle.adapt(BundleWiring.class);
 
 		if (bundle == null || bundleWiring == null) {
-			throw new IllegalArgumentException("Bundle, BundleContext or BundleWiring is null");
+			return Collections.emptySet();
 		}
 
 		Set<Bundle> bundles = new HashSet<>();
diff --git a/pax-web-spi/src/main/java/org/ops4j/pax/web/service/spi/servlet/OsgiServletContextClassLoader.java b/pax-web-spi/src/main/java/org/ops4j/pax/web/service/spi/servlet/OsgiServletContextClassLoader.java
index f9fe52e3c..29f3be7c4 100644
--- a/pax-web-spi/src/main/java/org/ops4j/pax/web/service/spi/servlet/OsgiServletContextClassLoader.java
+++ b/pax-web-spi/src/main/java/org/ops4j/pax/web/service/spi/servlet/OsgiServletContextClassLoader.java
@@ -25,6 +25,7 @@ import javax.servlet.ServletContext;
 
 import org.osgi.framework.Bundle;
 import org.osgi.framework.BundleReference;
+import org.osgi.framework.wiring.BundleWiring;
 
 /**
  * <p>A {@link ClassLoader} added in Pax Web to replace all pax-swissbox/xbean <em>bundle classloaders</em> and to be used
@@ -113,9 +114,11 @@ public class OsgiServletContextClassLoader extends ClassLoader implements Bundle
 	public Class<?> loadClass(String name) throws ClassNotFoundException {
 		List<Exception> suppressed = new ArrayList<>(bundles.size());
 		for (Bundle b : bundles) {
-			if (b.getState() != Bundle.UNINSTALLED) {
+			BundleWiring bw = b.adapt(BundleWiring.class);
+			ClassLoader cl = bw == null ? null : bw.getClassLoader();
+			if (cl != null) {
 				try {
-					return b.loadClass(name);
+					return cl.loadClass(name);
 				} catch (Exception e) {
 					suppressed.add(e);
 				}
@@ -130,8 +133,10 @@ public class OsgiServletContextClassLoader extends ClassLoader implements Bundle
 	@Override
 	protected URL findResource(String name) {
 		for (Bundle b : bundles) {
-			if (b.getState() != Bundle.UNINSTALLED) {
-				URL res = b.getResource(name);
+			BundleWiring bw = b.adapt(BundleWiring.class);
+			ClassLoader cl = bw == null ? null : bw.getClassLoader();
+			if (cl != null) {
+				URL res = cl.getResource(name);
 				if (res != null) {
 					return res;
 				}
@@ -145,8 +150,10 @@ public class OsgiServletContextClassLoader extends ClassLoader implements Bundle
 	protected Enumeration<URL> findResources(String name) throws IOException {
 		List<URL> urls = new ArrayList<>(32);
 		for (Bundle b : bundles) {
-			if (b.getState() != Bundle.UNINSTALLED) {
-				Enumeration<URL> e = b.getResources(name);
+			BundleWiring bw = b.adapt(BundleWiring.class);
+			ClassLoader cl = bw == null ? null : bw.getClassLoader();
+			if (cl != null) {
+				Enumeration<URL> e = cl.getResources(name);
 				if (e != null) {
 					while (e.hasMoreElements()) {
 						urls.add(e.nextElement());
```

Or if not, just please try with pax-web-api and pax-web-spi bundles from the attached ZIP: [gh1800.zip](https://github.com/ops4j/org.ops4j.pax.web/files/10091015/gh1800.zip)

**Comment by olfuerniss** [comment]
I've updated the 8.0.11 source code and build it locally.

I've done now over 50 re-deployments of the backend bundle (with Karaf restarts in between) and it seems to be fixed! :-) 

Thank you very much!

**Comment by grgrzybek** [comment]
Cool!
I can do a release then.

**Comment by olfuerniss** [comment]
JB has planned to release Karaf 4.4.3 on January 2023, hopefully with pax-web >= 8.0.14. This is a little bit late.

We build our custom Karaf 4.4.2. Is it the preferred way to replace just those two jar-files in [kara]/system/org/ops4j/pax/web/*. Or is there even a simpler way?

**Comment by grgrzybek** [comment]
If you create your own custom distro, just use `<blacklistedRepositories>` in `karaf-maven-plugin` configuration to blacklist the version used by Karaf 4.4.2 and add the new version of Pax Web.
```xml
<configuration>
...
    <bootFeatures>
        <feature>pax-web-http-jetty</feature>
        ...
    </bootFeatures>
    <blacklistedRepositories>
    ...
        <repository>mvn:org.ops4j.pax.web/pax-web-features/8.0.11/xml/features</repository>
    </blacklistedRepositories>
    <repositories>
    ...
        <repository>mvn:org.ops4j.pax.web/pax-web-features/8.0.14/xml/features</repository>
    </repositories>
</configuration>
```

**Comment by grgrzybek** [comment]
@olfuerniss Pax Web 8.0.14 should be in Maven Central in ~1 hour.

**Comment by olfuerniss** [comment]
@grgrzybek Thanks! Our custom Karaf 4.4.2 uses it already. :-)

**Comment by grgrzybek** [comment]
Great to hear - thanks for great cooperation!
