### ISSUE TITLE
org.eclipse.jetty.rewrite.RewriteCustomizer cannot be found with Karaf 4.4.2

### ISSUE THREAD

**Issue by ktschmidt** [ops4j/org.ops4j.pax.web#1817]
#1712 was raised and fixed last year related to this, but the class that could not be found in that issue was org.eclipse.jetty.rewrite.handler.RewriteHandler.  I happen to have a jetty.xml that uses org.eclipse.jetty.rewrite.RewriteCustomizer  in a different package and it cannot be found generating an error on Karaf start-up.

The issue appears to be that while I have org.eclipse.jetty.rewrite installed and it exports org.eclipse.jetty.rewrite, pax-web-jetty only imports org.eclipse.jetty.rewrite.handler and not org.eclipse.jetty.rewrite.

I'm not aware of a reason to omit that export so it was probably just an oversight?

This worked in prior versions (4.3.x).

**Comment by grgrzybek** [comment]
You're right - I'll add this import. Thanks for reporting!
