### ISSUE TITLE
Unable to start Pax-Web 8.0.6 by using PFX Certificate.

### ISSUE THREAD

**Issue by grgrzybek** [ops4j/org.ops4j.pax.web#1821]
See the thread: https://www.mail-archive.com/dev@karaf.apache.org/msg15992.html

**Comment by vamsi1027** [comment]
Hi @grgrzybek,

Did you get chance looking into this one. As per my understading  jetty side might be issue. Do you agree?

**Comment by grgrzybek** [comment]
Hello, thanks for answering here @vamsi1027.

Actually I asked you on the mailing list to provide full `jetty.xml` configuration because sole
```xml
<New class="org.eclipse.jetty.util.ssl.SslContextFactory"
...
```

is not enough (it worked for me without NPE, but no certificate was used in TLS handshake). May I ask you to attach full `jetty.xml` here?

**Comment by vamsi1027** [comment]
@grgrzybek 

My sincere apologies for delayed response.

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Configure PUBLIC "-//Mort Bay Consulting// DTD Configure//EN" "http://jetty.mortbay.org/configure.dtd">
<Configure class="org.eclipse.jetty.server.Server" id="Server">

    
    
    
    
    
    
    
    <Call name="addBean">
        <Arg>
            <New class="org.eclipse.jetty.plus.jaas.JAASLoginService">
                <Set name="name">karaf</Set>
                <Set name="loginModuleName">karaf</Set>
                <Set name="roleClassNames">
                    <Array type="java.lang.String">
                        <Item>org.apache.karaf.jaas.boot.principal.RolePrincipal
                        </Item>
                    </Array>
                </Set>
            </New>
        </Arg>
    </Call>
    <Call name="addBean">
        <Arg>
            <New class="org.eclipse.jetty.plus.jaas.JAASLoginService">
                <Set name="name">default</Set>
                <Set name="loginModuleName">karaf</Set>
                <Set name="roleClassNames">
                    <Array type="java.lang.String">
                        <Item>org.apache.karaf.jaas.boot.principal.RolePrincipal
                        </Item>
                    </Array>
                </Set>
            </New>
        </Arg>
    </Call>
    <Call name="addBean">
        <Arg>
            <New class="org.eclipse.jetty.plus.jaas.JAASLoginService">
                <Set name="name">admin</Set>
                <Set name="loginModuleName">admin</Set>
                <Set name="roleClassNames">
                    <Array type="java.lang.String">
                        <Item>org.apache.karaf.jaas.boot.principal.RolePrincipal
                        </Item>
                    </Array>
                </Set>
            </New>
        </Arg>
    </Call>
	<Call name="addBean">
        <Arg>
            <New class="org.eclipse.jetty.plus.jaas.JAASLoginService">
                <Set name="name">admin-certificate</Set>
                <Set name="loginModuleName">certificate</Set>
                <Set name="roleClassNames">
                    <Array type="java.lang.String">
                        <Item>org.apache.karaf.jaas.boot.principal.RolePrincipal
                        </Item>
                    </Array>
                </Set>
            </New>
        </Arg>
    </Call>
	
    <Call name="addBean">
        <Arg>
            <New class="org.eclipse.jetty.plus.jaas.JAASLoginService">
                <Set name="name">good-server-properties</Set>
                <Set name="loginModuleName">good-server-properties</Set>
                <Set name="roleClassNames">
                    <Array type="java.lang.String">
                        <Item>org.apache.karaf.jaas.boot.principal.RolePrincipal
                        </Item>
                    </Array>
                </Set>
            </New>
        </Arg>
    </Call>
    <Call name="addBean">
        <Arg>
            <New class="org.eclipse.jetty.plus.jaas.JAASLoginService">
                <Set name="name">server-db</Set>
                <Set name="loginModuleName">server-db</Set>
                <Set name="roleClassNames">
                    <Array type="java.lang.String">
                        <Item>org.apache.karaf.jaas.boot.principal.RolePrincipal
                        </Item>
                    </Array>
                </Set>
            </New>
        </Arg>
    </Call>

    
    
    

    
    
    

    <New class="org.eclipse.jetty.util.ssl.SslContextFactory" id="sslContextFactory">
        <Set name="KeyStorePath">
<SystemProperty default="." name="jetty.home"/>/etc/keystores/certificate.pfx</Set>
        <Set name="TrustStorePath">
<SystemProperty default="." name="jetty.home"/>/etc/keystores/certificate.pfx</Set>

        <Set name="KeyStorePassword">OBF:1wfy1kmm1uo51w1w1m4q1wu81l871bi81lfce1bi61l531wu61m7o1w1m1unt1kk01wg0</Set>
        <Set name="KeyManagerPassword">OBF:1wfy1kmm1uo51w1w1m4q1wu81l871bi81lflce1bi61l531wu61m7o1w1m1unt1kk01wg0</Set>
        <Set name="TrustStorePassword">OBF:1wfy1kmm1uo51w1w1m4q1wu81l871bi81lfce1bi61l531wu61m7o1w1m1unt1kk01wg0</Set>
        <Set name="KeyStoreType">PKCS12</Set>
        <Set name="TrustStoreType">PKCS12</Set>



        <Set name="ExcludeProtocols">
	    <Array type="java.lang.String">
		<Item>TLSv1.1</Item>
        <Item>TLSv1</Item>
		<Item>SSL</Item>
		<Item>SSLv2</Item>
		<Item>SSLv2Hello</Item>
		<Item>SSLv3</Item>
	    </Array>
	</Set>
	<Set name="ExcludeCipherSuites">
	    <Array type="java.lang.String">
            <Item>^(TLS_DH_|TLS_ECDH_|SSL_|.*_DHE_|.*_NULL_|.*_anon_|.*_GCM_|.*_3DES_|TLS_RSA_.*_SHA$).*|.*_(MD5)$</Item>

	    </Array>
	</Set>

    
    </New> 

    <New class="org.eclipse.jetty.server.HttpConfiguration" id="httpConfig">
        <Set name="secureScheme">https</Set>
        <Set name="securePort">
<Property default="8443" name="jetty.secure.port"/>
</Set>
        <Set name="outputBufferSize">32768</Set>
        <Set name="requestHeaderSize">8192</Set>
        <Set name="responseHeaderSize">8192</Set>
        <Set name="sendServerVersion">false</Set>
        <Set name="sendDateHeader">false</Set>
        <Set name="headerCacheSize">512</Set>
    </New>

    
    
    
    
    
    
    <New class="org.eclipse.jetty.server.HttpConfiguration" id="sslHttpConfig">
        <Arg>
<Ref refid="httpConfig"/>
</Arg>
        <Call name="addCustomizer">
            <Arg>
                <New class="org.eclipse.jetty.server.SecureRequestCustomizer">
                    <Arg type="boolean">
<Property default="true" name="jetty.ssl.sniHostCheck"/>
</Arg>
                </New>
            </Arg>
        </Call>
    </New>

     
     
     
     
    

	<Call name="addConnector">
		<Arg>
			<New class="org.eclipse.jetty.server.ServerConnector" id="sslConnector">
				<Arg name="server">
					<Ref refid="Server" />
				</Arg>
				<Arg name="acceptors" type="int">
					<Property default="-1" deprecated="ssl.acceptors" name="jetty.ssl.acceptors" />
				</Arg>
				<Arg name="selectors" type="int">
					<Property default="-1" deprecated="ssl.selectors" name="jetty.ssl.selectors" />
				</Arg>
				<Arg name="factories">
					<Array type="org.eclipse.jetty.server.ConnectionFactory">
						
					</Array>
				</Arg>

				<Set name="host">
					<Property deprecated="jetty.host" name="jetty.ssl.host" />
				</Set>
				<Set name="port">
					<Property default="8443" deprecated="ssl.port" name="jetty.ssl.port" />
				</Set>
				<Set name="name">127.0.0.1:8443</Set>
				<Set name="idleTimeout">
					<Property default="30000" deprecated="ssl.timeout"
						name="jetty.ssl.idleTimeout" />
				</Set>
				<Set name="soLingerTime">
					<Property default="-1" deprecated="ssl.soLingerTime" name="jetty.ssl.soLingerTime" />
				</Set>
				<Set name="acceptorPriorityDelta">
					<Property default="0" deprecated="ssl.acceptorPriorityDelta"
						name="jetty.ssl.acceptorPriorityDelta" />
				</Set>
				<Set name="acceptQueueSize">
					<Property default="0" deprecated="ssl.acceptQueueSize"
						name="jetty.ssl.acceptQueueSize" />
				</Set>
			</New>
		</Arg>
	</Call>
	
	    <Call name="addConnector">
        <Arg>
            <New id="sslConnectorUEM" class="org.eclipse.jetty.server.ServerConnector">
                <Arg name="server"><Ref refid="Server" /></Arg>
                <Arg name="acceptors" type="int"><Property name="jetty.ssl.acceptors" deprecated="ssl.acceptors" default="-1"/></Arg>
                <Arg name="selectors" type="int"><Property name="jetty.ssl.selectors" deprecated="ssl.selectors" default="-1"/></Arg>
                <Arg name="factories">
                    <Array type="org.eclipse.jetty.server.ConnectionFactory">
                        
                    </Array>
                </Arg>

                <Set name="host"><Property name="jetty.ssl.host" deprecated="jetty.host" /></Set>
                <Set name="port"><Property name="jetty.ssl.port" deprecated="ssl.port" default="9443" /></Set>
                <Set name="name">127.0.0.1:9443</Set>
                <Set name="idleTimeout"><Property name="jetty.ssl.idleTimeout" deprecated="ssl.timeout" default="30000"/></Set>
                <Set name="soLingerTime"><Property name="jetty.ssl.soLingerTime" deprecated="ssl.soLingerTime" default="-1"/></Set>
                <Set name="acceptorPriorityDelta"><Property name="jetty.ssl.acceptorPriorityDelta" deprecated="ssl.acceptorPriorityDelta" default="0"/></Set>
                <Set name="acceptQueueSize"><Property name="jetty.ssl.acceptQueueSize" deprecated="ssl.acceptQueueSize" default="0"/></Set>
            </New>
        </Arg>
    </Call>

    <Ref id="sslConnector">
        <Call name="addIfAbsentConnectionFactory">
            <Arg>
                <New class="org.eclipse.jetty.server.SslConnectionFactory">
                    <Arg name="next">http/1.1</Arg>
                    <Arg name="sslContextFactory"> <Ref refid="sslContextFactory"/>
				</Arg>
                </New>
            </Arg>
        </Call>	

        <Call name="addConnectionFactory">
            <Arg>
                <New class="org.eclipse.jetty.server.HttpConnectionFactory">
                    <Arg name="config">
						<Ref refid="sslHttpConfig"/>
					</Arg>
                </New>
            </Arg>
        </Call>
    </Ref>
	
	

    <Ref id="sslConnectorUEM">
        <Call name="addIfAbsentConnectionFactory">
            <Arg>
                <New class="org.eclipse.jetty.server.SslConnectionFactory">
                    <Arg name="next">http/1.1</Arg>
                    <Arg name="sslContextFactory"><Ref refid="sslContextFactory"/></Arg>
                </New>
            </Arg>
        </Call>

        <Call name="addConnectionFactory">
            <Arg>
                <New class="org.eclipse.jetty.server.HttpConnectionFactory">
                    <Arg name="config"><Ref refid="sslHttpConfig" /></Arg>
                </New>
            </Arg>
        </Call>
    </Ref>

</Configure>

**Comment by grgrzybek** [comment]
Hello @vamsi1027 I just checked with Karaf 4.4.3 and Pax Web 8.0.15 (included in Karaf 4.4.3) and after changing few things, everything actually worked...

See the logs, showing two SSL connectors (ports 8443 and 9443):
```
2023-01-23T12:54:04,426 | INFO  | paxweb-config-1-thread-1 (change controller) | AbstractConnector                | 63 - org.eclipse.jetty.util - 9.4.50.v20221201 | Started 127.0.0.1:8443@4d4f8c73{SSL, (ssl, http/1.1)}{0.0.0.0:8443}
2023-01-23T12:54:04,431 | INFO  | paxweb-config-1-thread-1 (change controller) | AbstractConnector                | 63 - org.eclipse.jetty.util - 9.4.50.v20221201 | Started 127.0.0.1:9443@34bb500b{SSL, (ssl, http/1.1)}{0.0.0.0:9443}
2023-01-23T12:54:04,436 | INFO  | paxweb-config-1-thread-1 (change controller) | AbstractConnector                | 63 - org.eclipse.jetty.util - 9.4.50.v20221201 | Started default@7cbe1411{HTTP/1.1, (http/1.1)}{0.0.0.0:8181}
2023-01-23T12:54:04,437 | INFO  | paxweb-config-1-thread-1 (change controller) | Server                           | 63 - org.eclipse.jetty.util - 9.4.50.v20221201 | Started @2817ms
```

Here are the changes I had to make:
* change `org.eclipse.jetty.plus.jaas.JAASLoginService` to `org.eclipse.jetty.jaas.JAASLoginService`
* you used `<SystemProperty default="." name="jetty.home"/>/etc/keystores/certificate.pfx`, however if `jetty.home` is undefined, it results in `./etc/keystores/certificate.pfx` which may be the issue (it was, in my case, when I simply tried to use absolute paths)
* also I used a P12 file with more certificates inside, so I had to change `org.eclipse.jetty.util.ssl.SslContextFactory` to `org.eclipse.jetty.util.ssl.SslContextFactory$Server`

Besides that, everything works as expected...

For diagnostic purposes, here's a full list of bundles I use:
```
karaf@root()> la -l
START LEVEL 100 , List Threshold: 0
ID │ State    │ Lvl │ Version            │ Location
───┼──────────┼─────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 0 │ Active   │   0 │ 7.0.5              │ System Bundle
 1 │ Resolved │   1 │ 4.4.3              │ mvn:org.apache.karaf.features/org.apache.karaf.features.extension/4.4.3
 2 │ Active   │   5 │ 2.6.12             │ mvn:org.ops4j.pax.url/pax-url-aether/2.6.12
 3 │ Active   │   5 │ 1.2.4              │ mvn:org.apache.felix/org.apache.felix.metatype/1.2.4
 4 │ Active   │   5 │ 4.4.3              │ mvn:org.apache.karaf.services/org.apache.karaf.services.eventadmin/4.4.3
 5 │ Active   │   8 │ 2.2.0              │ mvn:org.ops4j.pax.logging/pax-logging-api/2.2.0
 6 │ Active   │   8 │ 2.4.0              │ mvn:org.fusesource.jansi/jansi/2.4.0
 7 │ Active   │   8 │ 2.2.0              │ mvn:org.ops4j.pax.logging/pax-logging-log4j2/2.2.0
 8 │ Active   │   9 │ 1.2.0.202109301733 │ mvn:org.osgi/org.osgi.util.function/1.2.0
 9 │ Active   │   9 │ 1.2.0.202109301733 │ mvn:org.osgi/org.osgi.util.promise/1.2.0
10 │ Active   │   9 │ 1.0.2              │ mvn:org.apache.felix/org.apache.felix.coordinator/1.0.2
11 │ Active   │   9 │ 1.0.14             │ mvn:org.apache.felix/org.apache.felix.converter/1.0.14
12 │ Active   │  10 │ 1.9.26             │ mvn:org.apache.felix/org.apache.felix.configadmin/1.9.26
13 │ Active   │  11 │ 4.4.3              │ mvn:org.apache.karaf.config/org.apache.karaf.config.core/4.4.3
14 │ Active   │  11 │ 1.0.16             │ mvn:org.apache.felix/org.apache.felix.configurator/1.0.16
15 │ Active   │  11 │ 1.2.6              │ mvn:org.apache.felix/org.apache.felix.configadmin.plugin.interpolation/1.2.6
16 │ Active   │  11 │ 1.2.14             │ mvn:org.apache.sling/org.apache.sling.commons.johnzon/1.2.14
17 │ Active   │  11 │ 1.0.6              │ mvn:org.apache.felix/org.apache.felix.cm.json/1.0.6
18 │ Active   │  12 │ 3.7.4              │ mvn:org.apache.felix/org.apache.felix.fileinstall/3.7.4
19 │ Active   │  15 │ 4.4.3              │ mvn:org.apache.karaf.features/org.apache.karaf.features.core/4.4.3
20 │ Active   │  30 │ 1.70               │ mvn:org.bouncycastle/bcpkix-jdk15on/1.70
21 │ Active   │  30 │ 1.70               │ mvn:org.bouncycastle/bcprov-jdk15on/1.70
22 │ Active   │  30 │ 1.70               │ mvn:org.bouncycastle/bcutil-jdk15on/1.70
23 │ Active   │  30 │ 1.1.5              │ mvn:org.apache.aries.jmx/org.apache.aries.jmx.api/1.1.5
24 │ Active   │  30 │ 1.1.8              │ mvn:org.apache.aries.jmx/org.apache.aries.jmx.core/1.1.8
25 │ Active   │  30 │ 1.2.0              │ mvn:org.apache.aries.jmx/org.apache.aries.jmx.whiteboard/1.2.0
26 │ Active   │  20 │ 1.1.3              │ mvn:org.apache.aries/org.apache.aries.util/1.1.3
27 │ Active   │  30 │ 4.4.3              │ mvn:org.apache.karaf.bundle/org.apache.karaf.bundle.core/4.4.3
28 │ Active   │  26 │ 4.4.3              │ mvn:org.apache.karaf.deployer/org.apache.karaf.deployer.features/4.4.3
29 │ Active   │  24 │ 4.4.3              │ mvn:org.apache.karaf.deployer/org.apache.karaf.deployer.kar/4.4.3
30 │ Active   │  24 │ 4.4.3              │ mvn:org.apache.karaf.deployer/org.apache.karaf.deployer.wrap/4.4.3
31 │ Active   │  30 │ 4.4.3              │ mvn:org.apache.karaf.diagnostic/org.apache.karaf.diagnostic.core/4.4.3
32 │ Active   │  80 │ 4.4.3              │ mvn:org.apache.karaf/org.apache.karaf.event/4.4.3
33 │ Active   │  30 │ 4.4.3              │ mvn:org.apache.karaf.features/org.apache.karaf.features.command/4.4.3
34 │ Active   │  30 │ 4.4.3              │ mvn:org.apache.karaf.instance/org.apache.karaf.instance.core/4.4.3
35 │ Active   │  30 │ 4.4.3              │ mvn:org.apache.karaf.jaas/org.apache.karaf.jaas.command/4.4.3
36 │ Active   │  30 │ 4.4.3              │ mvn:org.apache.karaf.jaas/org.apache.karaf.jaas.config/4.4.3
37 │ Active   │  30 │ 4.4.3              │ mvn:org.apache.karaf.jaas/org.apache.karaf.jaas.modules/4.4.3
38 │ Active   │  30 │ 4.4.3              │ mvn:org.apache.karaf.kar/org.apache.karaf.kar.core/4.4.3
39 │ Active   │  30 │ 4.4.3              │ mvn:org.apache.karaf.log/org.apache.karaf.log.core/4.4.3
40 │ Active   │  30 │ 4.4.3              │ mvn:org.apache.karaf.management/org.apache.karaf.management.server/4.4.3
41 │ Active   │  30 │ 4.4.3              │ mvn:org.apache.karaf.package/org.apache.karaf.package.core/4.4.3
42 │ Active   │  30 │ 4.4.3              │ mvn:org.apache.karaf.service/org.apache.karaf.service.core/4.4.3
43 │ Active   │  30 │ 4.4.3              │ mvn:org.apache.karaf.shell/org.apache.karaf.shell.commands/4.4.3
44 │ Active   │  30 │ 4.4.3              │ mvn:org.apache.karaf.shell/org.apache.karaf.shell.core/4.4.3
45 │ Active   │  30 │ 4.4.3              │ mvn:org.apache.karaf.shell/org.apache.karaf.shell.ssh/4.4.3
46 │ Active   │  30 │ 4.4.3              │ mvn:org.apache.karaf.system/org.apache.karaf.system.core/4.4.3
47 │ Active   │  30 │ 2.9.2              │ mvn:org.apache.sshd/sshd-osgi/2.9.2
48 │ Active   │  30 │ 2.9.2              │ mvn:org.apache.sshd/sshd-scp/2.9.2
49 │ Active   │  30 │ 2.9.2              │ mvn:org.apache.sshd/sshd-sftp/2.9.2
50 │ Active   │  30 │ 3.21.0             │ mvn:org.jline/jline/3.21.0
51 │ Active   │  10 │ 2.6.12             │ mvn:org.ops4j.pax.url/pax-url-wrap/2.6.12/jar/uber
52 │ Active   │  30 │ 4.0.0              │ mvn:jakarta.servlet/jakarta.servlet-api/4.0.4
53 │ Active   │  30 │ 9.4.50.v20221201   │ mvn:org.eclipse.jetty/jetty-client/9.4.50.v20221201
54 │ Active   │  30 │ 9.4.50.v20221201   │ mvn:org.eclipse.jetty/jetty-continuation/9.4.50.v20221201
55 │ Active   │  30 │ 9.4.50.v20221201   │ mvn:org.eclipse.jetty/jetty-http/9.4.50.v20221201
56 │ Active   │  30 │ 9.4.50.v20221201   │ mvn:org.eclipse.jetty/jetty-io/9.4.50.v20221201
57 │ Active   │  30 │ 9.4.50.v20221201   │ mvn:org.eclipse.jetty/jetty-jaas/9.4.50.v20221201
58 │ Active   │  30 │ 9.4.50.v20221201   │ mvn:org.eclipse.jetty/jetty-jmx/9.4.50.v20221201
59 │ Active   │  30 │ 9.4.50.v20221201   │ mvn:org.eclipse.jetty/jetty-security/9.4.50.v20221201
60 │ Active   │  30 │ 9.4.50.v20221201   │ mvn:org.eclipse.jetty/jetty-server/9.4.50.v20221201
61 │ Active   │  30 │ 9.4.50.v20221201   │ mvn:org.eclipse.jetty/jetty-servlet/9.4.50.v20221201
62 │ Active   │  30 │ 9.4.50.v20221201   │ mvn:org.eclipse.jetty/jetty-servlets/9.4.50.v20221201
63 │ Active   │  30 │ 9.4.50.v20221201   │ mvn:org.eclipse.jetty/jetty-util/9.4.50.v20221201
64 │ Active   │  30 │ 9.4.50.v20221201   │ mvn:org.eclipse.jetty/jetty-util-ajax/9.4.50.v20221201
65 │ Active   │  30 │ 9.4.50.v20221201   │ mvn:org.eclipse.jetty/jetty-xml/9.4.50.v20221201
66 │ Active   │  30 │ 8.0.15             │ mvn:org.ops4j.pax.web/pax-web-api/8.0.15
67 │ Resolved │  30 │ 8.0.15             │ mvn:org.ops4j.pax.web/pax-web-compatibility-servlet31/8.0.15
68 │ Active   │  30 │ 8.0.15             │ mvn:org.ops4j.pax.web/pax-web-jetty/8.0.15
69 │ Active   │  30 │ 8.0.15             │ mvn:org.ops4j.pax.web/pax-web-runtime/8.0.15
70 │ Active   │  30 │ 8.0.15             │ mvn:org.ops4j.pax.web/pax-web-spi/8.0.15
71 │ Active   │  30 │ 8.0.15             │ mvn:org.ops4j.pax.web/pax-web-tomcat-common/8.0.15
```

can you show your list of bundles? Could you try with Karaf 4.4.3?

**Comment by grgrzybek** [comment]
@vamsi1027 hi - any feedback? I hope the above explanation is enough for you to configure JSF correctly.

**Comment by grgrzybek** [comment]
@vamsi1027 hi - is the configuration working?

**Comment by grgrzybek** [comment]
@vamsi1027 any news about this one?

**Comment by grgrzybek** [comment]
@vamsi1027 I'm closing this issue now. If you believe there still is a problem, please reopen or create new issue.
