### ISSUE TITLE
[9.0.x] Add repackaged Keycloak 21

### ISSUE THREAD

**Issue by Maurice-Betzel** [ops4j/org.ops4j.pax.web#1834]
Repackages proper Keycloak 21 libraries due to not all of them are proper OSGi bundles.

**Comment by grgrzybek** [comment]
Well - we'll do it in next release ;) For now, Keycloak 20 bundles should suffice.

**Comment by grgrzybek** [comment]
Thanks @Maurice-Betzel !

**Comment by Maurice-Betzel** [comment]
Hi Grzegorz, you are fast, I was just following the readme where you stated that a issue must be filed first :)

**Comment by grgrzybek** [comment]
@Maurice-Betzel FYI, I've combined `pax-web-keycloak20` and your `pax-web-keycloak21` into just `pax-web-keycloak` keeping `pax-web-keycloak18` as-is.
So next time when Keycloak 22 is released, we'll simply bump Keycloak version from 21 to 22 without multiplying the artifacts ;)

I also tested the whiteboard security example and it works (see: https://github.com/ops4j/org.ops4j.pax.web/tree/web-8.0.17/samples/samples-whiteboard/whiteboard-security)

**Comment by Maurice-Betzel** [comment]
I will be using it with Vaadin and I definitely understand the ‘while you’re in it’. But I have got to solve the DOSGi Java serialization with Apache Avro first, but it is in its final stages though.
