### ISSUE TITLE
pax-web-jetty-keycloak 8.0.17: version range of org.apache.httpcomponents.httpclient is very small

### ISSUE THREAD

**Issue by Maurice-Betzel** [ops4j/org.ops4j.pax.web#1837]
Hi Grzegorz,

the version range of org.apache.httpcomponents.httpclient in pax-web-jetty-keycloak is very small (version>=4.4.0)(!(version>=4.5.0))). Could this be upped to 5.x? Seems to be comming from Keycloak.

karaf@root()> feature:install pax-web-jetty-keycloak
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=pax-web-jetty-keycloak; type=karaf.feature; version="[8.0.17,8.0.17]"; filter:="(&(osgi.identity=pax-web-jetty-keycloak)(type=karaf.feature)(version>=8.0.17)(version<=8.0.17))" [caused by: Unable to resolve pax-web-jetty-keycloak/8.0.17: missing requirement [pax-web-jetty-keycloak/8.0.17] osgi.identity; osgi.identity=keycloak-adapter-core; type=karaf.feature [caused by: Unable to resolve keycloak-adapter-core/8.0.17: missing requirement [keycloak-adapter-core/8.0.17] osgi.identity; osgi.identity=org.ops4j.pax.web.keycloak-common; type=osgi.bundle; version="[8.0.17,8.0.17]"; resolution:=mandatory [caused by: Unable to resolve org.ops4j.pax.web.keycloak-common/8.0.17: missing requirement [org.ops4j.pax.web.keycloak-common/8.0.17] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.apache.http.client.config)(version>=4.5.0)(!(version>=5.0.0)))" [caused by: Unable to resolve org.apache.httpcomponents.httpclient/4.5.14: missing requirement [org.apache.httpcomponents.httpclient/4.5.14] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.apache.http)(version>=4.4.0)(!(version>=4.5.0)))"]]]]

**Comment by grgrzybek** [comment]
Hello

If you check:
 - https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore-osgi/
 - https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient-osgi/

the development of httpclient4 / httpcore4 stopped at 4.5 / 4.4
respectively. Version 5 has different package names and there are no OSGi
versions of HttpClient/Core 5....

But it works for me on fresh Karaf 4.4.3...

***@***.***()> feature:install -v pax-web-jetty-keycloak



Adding features: pax-web-jetty-keycloak/[8.0.17,8.0.17]
Changes to perform:
  Region: root
    Bundles to install:
      mvn:com.fasterxml.jackson.core/jackson-annotations/2.14.2
      mvn:com.fasterxml.jackson.core/jackson-core/2.14.2
      mvn:com.fasterxml.jackson.core/jackson-databind/2.14.2
      mvn:jakarta.servlet/jakarta.servlet-api/4.0.4
      mvn:org.apache.httpcomponents/httpclient-osgi/4.5.14
      mvn:org.apache.httpcomponents/httpcore-osgi/4.4.16
      mvn:org.eclipse.jetty/jetty-client/9.4.50.v20221201
      mvn:org.eclipse.jetty/jetty-continuation/9.4.50.v20221201
      mvn:org.eclipse.jetty/jetty-http/9.4.50.v20221201
      mvn:org.eclipse.jetty/jetty-io/9.4.50.v20221201
      mvn:org.eclipse.jetty/jetty-jaas/9.4.50.v20221201
      mvn:org.eclipse.jetty/jetty-jmx/9.4.50.v20221201
      mvn:org.eclipse.jetty/jetty-security/9.4.50.v20221201
      mvn:org.eclipse.jetty/jetty-server/9.4.50.v20221201
      mvn:org.eclipse.jetty/jetty-servlet/9.4.50.v20221201
      mvn:org.eclipse.jetty/jetty-servlets/9.4.50.v20221201
      mvn:org.eclipse.jetty/jetty-util/9.4.50.v20221201
      mvn:org.eclipse.jetty/jetty-util-ajax/9.4.50.v20221201
      mvn:org.eclipse.jetty/jetty-xml/9.4.50.v20221201
      mvn:org.ops4j.pax.web/keycloak-common/8.0.17
      mvn:org.ops4j.pax.web/keycloak-osgi-adapter/8.0.17
      mvn:org.ops4j.pax.web/pax-web-api/8.0.17
      mvn:org.ops4j.pax.web/pax-web-compatibility-servlet31/8.0.17
      mvn:org.ops4j.pax.web/pax-web-jetty/8.0.17
      mvn:org.ops4j.pax.web/pax-web-jetty-keycloak/8.0.17
      mvn:org.ops4j.pax.web/pax-web-runtime/8.0.17
      mvn:org.ops4j.pax.web/pax-web-spi/8.0.17
      mvn:org.ops4j.pax.web/pax-web-tomcat-common/8.0.17
...

Which Karaf version do you use?

regards
Grzegorz Grzybek

wt., 28 lut 2023 o 16:17 Maurice Betzel ***@***.***>
napisał(a):

**Comment by Maurice-Betzel** [comment]
Just saw it was my bad, I had http core filtered out of my build. Building a Karaf distro the whole day makes bundles flying before my eyes. Time to do something else :).

**Comment by Maurice-Betzel** [comment]
It is a Karaf 4.4.3 custom build:
![image](https://user-images.githubusercontent.com/16353975/221906772-74b8c76e-1fc0-4973-84f7-24feaf1b29fd.png)
