### ISSUE TITLE
[8.0.x] Jetty WebSockerServerContainer.initialize() can't find context params

### ISSUE THREAD

**Issue by grgrzybek** [ops4j/org.ops4j.pax.web#1838]
https://groups.google.com/g/ops4j/c/tav8NIH3aLM/m/DtpUDEUVBQAJ

**Comment by infiniteuniverse1** [comment]
Hi thanks for opening this ticket. Here's what I've discovered to this point from debugging the code. When the Jetty WebSocketServerContainerInitializer.onStartup is getting called, it was passed an instance of [OsgiDynamicServletContext](https://github.com/ops4j/org.ops4j.pax.web/blob/pax-web-8.0.x/pax-web-spi/src/main/java/org/ops4j/pax/web/service/spi/servlet/OsgiDynamicServletContext.java) which contains in it an instance of [OsgiServletContext](https://github.com/ops4j/org.ops4j.pax.web/blob/pax-web-8.0.x/pax-web-spi/src/main/java/org/ops4j/pax/web/service/spi/servlet/OsgiServletContext.java) which in turn contains a reference to an [OsgiContextModel](https://github.com/ops4j/org.ops4j.pax.web/blob/pax-web-8.0.x/pax-web-spi/src/main/java/org/ops4j/pax/web/service/spi/model/OsgiContextModel.java) which contains in its contextParams attribute the "org.eclipse.jetty.websocket.jsr356.addDynamicFilter" -> "false" context parameter. However, here on line [267](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-websocket/javax-websocket-server-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/server/deploy/WebSocketServerContainerInitializer.java#L267) jetty doesn't directly use that context but instead performs initialization using the ServletContextHandler that it looked up, which is an instance of [PaxWebServletContextHandler](https://github.com/ops4j/org.ops4j.pax.web/blob/pax-web-8.0.x/pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/PaxWebServletContextHandler.java). While the PaxWebServletContextHandler instance does contain in its osgiServletContext attribute a reference to the original OsgiDynamicServletContext, here on line [217](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-websocket/javax-websocket-server-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/server/deploy/WebSocketServerContainerInitializer.java#L217) in the initialize call, the getServletContext call is not overridden by PaxWebServletContextHandler so it ultimately delegates down to the underlying [ContextHandler](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java) which only searches its internal _initParams attribute when the context parameter is searched for [here](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-websocket/javax-websocket-server-impl/src/main/java/org/eclipse/jetty/websocket/jsr356/server/deploy/WebSocketServerContainerInitializer.java#L103).

**Comment by grgrzybek** [comment]
Got it - your analysis is correct and I know exactly where's the problem and I can fix it ;) But next week, ok?

**Comment by infiniteuniverse1** [comment]
Sure, that would be great, thanks!

**Comment by infiniteuniverse1** [comment]
BTW, meant to mention, the above analysis was based upon Pax Web version 8.0.6 with Jetty 9.4.48.v20220622

**Comment by grgrzybek** [comment]
In the meantime, could you please check with Pax Web 8.0.17?

**Comment by infiniteuniverse1** [comment]
It looks like the issue was resolved by the context parameter copy in the JettyServerWrapper (lines 2176-2179) that was added in the Pax Web 8.0.x stream by [this commit](https://github.com/ops4j/org.ops4j.pax.web/commit/596577b106a811cbcb2864e9ce4d7475c62eeb45).

**Comment by grgrzybek** [comment]
Fixd with #1716 where better context param handling was used.
