### ISSUE TITLE
how to mvn clean install org.ops4j.pax.web-web-7.2.29

### ISSUE THREAD

**Issue by HousionQ** [ops4j/org.ops4j.pax.web#1863]
I used the open source project pentaho kettle, but the version of Jettye he cited was too low and had insecure vulnerabilities. I first upgraded to the latest Jetty in maven-parent-poms-9.3.0.0-R, but pentaho also quoted karaf through me The final lock of the troubleshooting is org.ops4j.pax.web-web-7.2.29. I want to modify the Jetty referenced here, and it appears when recompiling

![image](https://github.com/ops4j/org.ops4j.pax.web/assets/20298856/801724c1-0074-4104-8f9c-b31e3d6033bd)

I go to https://mvnrepository.com/artifact/org.springframework/org.springframework.web?repo=geomajas

The search found that this version is only available in the geomajas warehouse, but I can no longer access this warehouse, and the final compilation is stuck here and cannot be resolved.

![image](https://github.com/ops4j/org.ops4j.pax.web/assets/20298856/9f531183-2726-4573-a14b-88287b48b6c5)

My compile command is mvn clean install -DskipTests '-Drat.skip=true'

**Comment by grgrzybek** [comment]
Hello

Pax Web 7.2 is no longer maintained. You should use version 8.0.20 which contains latest versions of Jetty, Tomcat and Undertow servlet runtimes.

**Comment by HousionQ** [comment]
Thank you for your reply, I will try it and hope that 8.0.20 will be fully compatible with 7.2.29
