### ISSUE TITLE
[8.0.x] Pax-Web-Tomcat removes all external valves, container listeners, and lifecycle listeners

### ISSUE THREAD

**Issue by stsiano** [ops4j/org.ops4j.pax.web#1896]
After an upgrade from Karaf 4.4.3 to Karaf 4.4.4 our custom authentication valve in Tomcat stopped working.

A closer analysis showed that the code that was added with the fix for issue #1716 removes all valves, container listeners and lifecycle listeners that are not from the packages org.apache.tomcat, org.apache.catalina, or org.ops4j.pax.web without even writing a log about it.

As a workaround I could move our valve to an org.ops4j.pax.web package and now it works, but I still think that silently removing all external valves from the configuration is a bit drastic. I don't use keycloak, so I don't know what to expect from that side. Isn't it possible to block only some valves from the configuration and keep all others instead of keeping only the content from these three internal packages)?

**Comment by grgrzybek** [comment]
Thanks for reporting @stsiano !
Indeed, bec0ade90057f6f2c32304e2a2202acd33cfbbf3 removes "extra" valves. I think I added this removal simply because I saw some duplication after several restarts/refreshes...

May I get more information? How do you add your valves in the first place?

**Comment by stsiano** [comment]
The authentication valve where I noticed the issue is added via context.xml, which is configured via
org.ops4j.pax.web.context.file = config/context.xml in org.ops4j.pax.web.cfg. I don't know if any of the artifacts that are configured in the tomcat-server.xml configured via org.ops4j.pax.web.config.file = config/tomcat-server.xml
are also affected.

**Comment by grgrzybek** [comment]
So the bug is not the removal of "extra" valves, but rather not adding them back from context.xml - thanks! I'll check soon (too busy now).

**Comment by stsiano** [comment]
Well, the removal of the extra valves is done after the configurations are read (and they are not added). After the removal part is a configuration of the login. At this point in time the extra authenticator valve must be there, otherwise the code will add another login configuration. In any case, I don't see any of the removed artifacts getting removed again.

I actually don't understand why these extra valves and listeners are actually removed. If the purpose is to remove some leftover stuff when the container is re-initialized, it might be possible to move that before the configuration is read.

**Comment by grgrzybek** [comment]
Thanks for checking! I'll run the itests and if everything is :green_circle: I'll do a release next week (more or less).
