### ISSUE TITLE
[8.0.x] Pax Web session cookie config property org.ops4j.pax.web.session.cookie.secure = true is not applied on http connections

### ISSUE THREAD

**Issue by immilev** [ops4j/org.ops4j.pax.web#1925]
When using pax-web-jetty feature version 9.4.52.v20230823 (as included in Karaf 4.4.4), the Secure flag on the http session cookie config should be set if the property **org.ops4j.pax.web.session.cookie.secure** is set to **true**.  This should be the case, irrespective of the connector type (http or https).

Steps to reproduce:

1. Install Pax Web 8 and Pax Web Jetty 9 features in the default/standard Karaf 4.4.4 distribution
2. Set the **org.ops4j.pax.web.session.cookie.secure** to **true** in etc/org.ops4j.pax.web.cfg file.
3. In a Java Servlet or JSP, the request.getServletContext().getSessionCookieConfig().isSecure() where request is an instance of HttpServletRequest should return true. 

The session config has been set to use Secure cookies after all. The fact that cookie with the Secure flag may not be sent over an unencrypted connection should be irrelevant - the http connection to the app server may be proxied; the client connection to the UA will be over https.

Please note, that calling https://eclipse.dev/jetty/javadoc/jetty-9/org/eclipse/jetty/server/session/SessionHandler.CookieConfig.html#setSecure(true) via jetty-web.xml IoC config, does not affect the value returned by the default servlet context as per the above. Interestingly, the Set-Cookie header gets generated correctly in this case and includes the Security flag, but the Java Servlet API isSecure() call still returns false.

Thank you Grzegorz!

**Comment by grgrzybek** [comment]
Thanks @immilev for report. I fixed it and 8.0.26 release should be ready soon.
